services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_QUILVIAN: "http://160.20.104.98/api" # Pastikan ini ada!
    container_name: quilvian-frontend-container
    ports:
      - "8001:3000"
    environment:
      - NEXT_PUBLIC_API_QUILVIAN=http://160.20.104.98/api  # Pastikan ini juga ada!
