version: "3.8"

services:
  quilvian-frontend:
    build: .
    image: rizkigunawan/quilvian-system-frontend:latest
    ports:
      - "80:3000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
