version: "3.8"

services:
  quilvian-system-frontend-dev:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    restart: always
    volumes:
      - ./logs:/var/log/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
