
// import "./globals.css";
// import '../style/bootstrap.min.css'
// import '../style/typography.css'
// import '../style/style.css'
// import '../style/style-rtl.css'
// import '../style/responsive.css'
// import './assets/fullcalendar/core/main.css'
// import './assets/fullcalendar/daygrid/main.css'
// import './assets/fullcalendar/timegrid/main.css'
// import './assets/fullcalendar/list/main.css'
// import '../style/flatpickr.min.css'
// import dynamic from 'next/dynamic'
// import "choices.js/public/assets/styles/choices.min.css";
// import "flatpickr/dist/flatpickr.css";

// const ScrollLayout = dynamic(() => import('../components/ui/scrollLayout'), {ssr: false});

export const metadata = {
  title: "Quilvian System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
                      {children}
      </body>
    </html>
  );
}
