export const dataPerjanjian = [
  {
    id: 1,
    nomorRekamMedis: "90-22-12-80-016",
    nama: "Doni Wijayanto",
    no_registrasi: "12345",
    penjamin: "BPJS Kesehatan",
    tel_regis: "081234567890",
    dokter: "Dr. Rahmat Pratama",
    departemen: "Poli Anak",
    user: "Siti Rahmawati",
  },
  {
    id: 2,
    nomorRekamMedis: "90-22-12-80-017",
    nama: "Nurul Aisyah",
    no_registrasi: "12346",
    penjamin: "Mandiri",
    tel_regis: "081345678901",
    dokter: "Dr. Indra Wijaya",
    departemen: "Poli Penyakit Dalam",
    user: "Andi Saputra",
  },
  {
    id: 3,
    nomorRekamMedis: "90-22-12-80-018",
    nama: "Siti Marlina",
    no_registrasi: "12347",
    penjamin: "BPJS Kesehatan",
    tel_regis: "081456789012",
    dokter: "Dr. Maria Yunita",
    departemen: "Poli Mata",
    user: "Dewi Kusuma",
  },
  {
    id: 4,
    nomorRekamMedis: "90-22-12-80-019",
    nama: "Ahmad Faisal",
    no_registrasi: "12348",
    penjamin: "BPJS Kesehatan",
    tel_regis: "081567890123",
    dokter: "Dr. Bambang Setiawan",
    departemen: "Poli Kandungan",
    user: "Rahmawati Fajri",
  },
  {
    id: 5,
    nomorRekamMedis: "90-22-12-80-020",
    nama: "Hana Putri",
    no_registrasi: "12349",
    penjamin: "Mandiri",
    tel_regis: "081678901234",
    dokter: "Dr. Rizky Aditya",
    departemen: "Poli Psikiatri",
    user: "Andi Wijaya",
  },
  {
    id: 6,
    nomorRekamMedis: "90-22-12-80-021",
    nama: "Rama Nugraha",
    no_registrasi: "12350",
    penjamin: "BPJS Kesehatan",
    tel_regis: "081789012345",
    dokter: "Dr. Susi Yulianti",
    departemen: "Poli THT",
    user: "Rina Setiawan",
  },
  {
    id: 7,
    nomorRekamMedis: "90-22-12-80-022",
    nama: "Fadilah Nur",
    no_registrasi: "12351",
    penjamin: "Mandiri",
    tel_regis: "081890123456",
    dokter: "Dr. Hendro Kusuma",
    departemen: "Poli Bedah",
    user: "Farhan Akbar",
  },
  {
    id: 8,
    nomorRekamMedis: "90-22-12-80-023",
    nama: "Rizky Ardian",
    no_registrasi: "12352",
    penjamin: "BPJS Kesehatan",
    tel_regis: "081901234567",
    dokter: "Dr. Anita Sari",
    departemen: "Poli Kulit",
    user: "Dina Pratiwi",
  },
  {
    id: 9,
    nomorRekamMedis: "90-22-12-80-024",
    nama: "Salsa Ayu",
    no_registrasi: "12353",
    penjamin: "BPJS Kesehatan",
    tel_regis: "082012345678",
    dokter: "Dr. Yoga Pratama",
    departemen: "Poli Jantung",
    user: "Agung Prihanto",
  },
  {
    id: 10,
    nomorRekamMedis: "90-22-12-80-025",
    nama: "Daffa Pramudya",
    no_registrasi: "12354",
    penjamin: "Mandiri",
    tel_regis: "082123456789",
    dokter: "Dr. Lina Hartati",
    departemen: "Poli Saraf",
    user: "Nina Kusnadi",
  },
  {
    id: 11,
    nomorRekamMedis: "90-22-12-80-026",
    nama: "Rina Anggraeni",
    no_registrasi: "12355",
    penjamin: "BPJS Kesehatan",
    tel_regis: "082234567890",
    dokter: "Dr. Budi Kurniawan",
    departemen: "Poli Urologi",
    user: "Anita Pramesti",
  },
  {
    id: 12,
    nomorRekamMedis: "90-22-12-80-027",
    nama: "Zaki Ahmad",
    no_registrasi: "12356",
    penjamin: "BPJS Kesehatan",
    tel_regis: "082345678901",
    dokter: "Dr. Diana Sari",
    departemen: "Laboratorium Patologi",
    user: "Heri Santoso",
  },
  {
    id: 13,
    nomorRekamMedis: "90-22-12-80-028",
    nama: "Farah Lestari",
    no_registrasi: "12357",
    penjamin: "Mandiri",
    tel_regis: "082456789012",
    dokter: "Dr. Ali Fikri",
    departemen: "Radiologi",
    user: "Nurhayati Anwar",
  },
  {
    id: 14,
    nomorRekamMedis: "90-22-12-80-029",
    nama: "Alif Budiman",
    no_registrasi: "12358",
    penjamin: "BPJS Kesehatan",
    tel_regis: "082567890123",
    dokter: "Dr. Erna Yulianti",
    departemen: "Poli Kulit",
    user: "Sandi Prakoso",
  },
  {
    id: 15,
    nomorRekamMedis: "90-22-12-80-030",
    nama: "Rani Pratiwi",
    no_registrasi: "12359",
    penjamin: "Mandiri",
    tel_regis: "082678901234",
    dokter: "Dr. Bayu Pratama",
    departemen: "Poli Anak",
    user: "Laila Anindya",
  },
];

export const dataReservasi = [
  {
    id: 1,
    nomorRekamMedis: "90-22-12-80-001",
    nama: "Ahmad Syafrudin",
    alamat: "Jl. Merpati No.12, Jakarta",
    tempat_lahir: "Jakarta",
    tanggal_lahir: "1990-01-01",
    penjamin: "BPJS",
  },
  {
    id: 2,
    nomorRekamMedis: "90-22-12-80-002",
    nama: "Dewi Lestari",
    alamat: "Jl. Anggrek No.7, Bandung",
    tempat_lahir: "Bandung",
    tanggal_lahir: "1985-05-05",
    penjamin: "Pribadi",
  },
  {
    id: 3,
    nomorRekamMedis: "90-22-12-80-003",
    nama: "Budi Hartono",
    alamat: "Jl. Kenanga No.10, Surabaya",
    tempat_lahir: "Surabaya",
    tanggal_lahir: "1988-03-15",
    penjamin: "Asuransi",
  },
  {
    id: 4,
    nomorRekamMedis: "90-22-12-80-004",
    nama: "Citra Dewi",
    alamat: "Jl. Melati No.8, Medan",
    tempat_lahir: "Medan",
    tanggal_lahir: "1992-07-20",
    penjamin: "BPJS",
  },
  {
    id: 5,
    nomorRekamMedis: "90-22-12-80-005",
    nama: "Siti Aminah",
    alamat: "Jl. Mawar No.3, Bekasi",
    tempat_lahir: "Bekasi",
    tanggal_lahir: "1995-09-12",
    penjamin: "BPJS",
  },
  {
    id: 6,
    nomorRekamMedis: "90-22-12-80-006",
    nama: "Hendri Saputra",
    alamat: "Jl. Cendrawasih No.15, Malang",
    tempat_lahir: "Malang",
    tanggal_lahir: "1987-11-25",
    penjamin: "Pribadi",
  },
  {
    id: 7,
    nomorRekamMedis: "90-22-12-80-007",
    nama: "Lina Mariska",
    alamat: "Jl. Jambu No.21, Tangerang",
    tempat_lahir: "Tangerang",
    tanggal_lahir: "1993-06-10",
    penjamin: "Asuransi",
  },
  {
    id: 8,
    nomorRekamMedis: "90-22-12-80-008",
    nama: "Agus Supriyanto",
    alamat: "Jl. Mangga No.4, Depok",
    tempat_lahir: "Depok",
    tanggal_lahir: "1980-02-17",
    penjamin: "BPJS",
  },
  {
    id: 9,
    nomorRekamMedis: "90-22-12-80-009",
    nama: "Nina Susanti",
    alamat: "Jl. Apel No.8, Bogor",
    tempat_lahir: "Bogor",
    tanggal_lahir: "1994-12-05",
    penjamin: "Pribadi",
  },
  {
    id: 10,
    nomorRekamMedis: "90-22-12-80-010",
    nama: "Andi Kurniawan",
    alamat: "Jl. Rambutan No.9, Yogyakarta",
    tempat_lahir: "Yogyakarta",
    tanggal_lahir: "1991-04-23",
    penjamin: "Asuransi",
  },
  {
    id: 11,
    nomorRekamMedis: "90-22-12-80-011",
    nama: "Tina Rahmawati",
    alamat: "Jl. Durian No.2, Semarang",
    tempat_lahir: "Semarang",
    tanggal_lahir: "1989-08-14",
    penjamin: "BPJS",
  },
  {
    id: 12,
    nomorRekamMedis: "90-22-12-80-012",
    nama: "Rudi Hartono",
    alamat: "Jl. Sawo No.11, Palembang",
    tempat_lahir: "Palembang",
    tanggal_lahir: "1983-03-30",
    penjamin: "Pribadi",
  },
  {
    id: 13,
    nomorRekamMedis: "90-22-12-80-013",
    nama: "Fina Ramadhani",
    alamat: "Jl. Duku No.7, Makassar",
    tempat_lahir: "Makassar",
    tanggal_lahir: "1996-07-11",
    penjamin: "Asuransi",
  },
  {
    id: 14,
    nomorRekamMedis: "90-22-12-80-014",
    nama: "Eka Wijaya",
    alamat: "Jl. Belimbing No.5, Denpasar",
    tempat_lahir: "Denpasar",
    tanggal_lahir: "1990-01-18",
    penjamin: "BPJS",
  },
  {
    id: 15,
    nomorRekamMedis: "90-22-12-80-015",
    nama: "Yuni Ariska",
    alamat: "Jl. Nangka No.13, Pontianak",
    tempat_lahir: "Pontianak",
    tanggal_lahir: "1984-10-25",
    penjamin: "Pribadi",
  },
];

export const dataODC = [
  {
    id: 1,
    nomorRekamMedis: "90-22-12-80-001",
    jamMasuk: "08:15",
    nama: "Sukaria Dewi",
    penjamin: "Pribadi",
    alamat: "Gading Serpong Blok B, Jalan Cinta No. 20, Tangerang",
    telepon: "081123456789",
    dokter: "Dr. Budi Santoso, Sp.KK",
    departemen: "Poli Kulit",
    user: "Admin A",
    userEdit: "Admin B",
    tanggalInput: "2023-12-01",
    tanggalEdit: "2023-12-02",
    kontrak:
      "BY PHONE: TINDAKAN UNTUK ANAK DENGAN KONSULTASI KONTROL DALAM 2 MINGGU",
    informasiLain:
      "PERIKSA UJI LAB KE RS DENGAN FORM LAB UNTUK ANALISIS DARAH LENGKAP",
  },
  {
    id: 2,
    nomorRekamMedis: "90-22-12-80-002",
    jamMasuk: "10:30",
    nama: "Rama Nugraha",
    penjamin: "BPJS",
    alamat: "Jl. Kenangan No. 15, Depok",
    telepon: "081234567890",
    dokter: "Dr. Indra Wijaya, Sp.PD",
    departemen: "Poli Penyakit Dalam",
    user: "Admin B",
    userEdit: "Admin C",
    tanggalInput: "2023-11-28",
    tanggalEdit: "2023-11-30",
    kontrak: "BY PHONE: TINDAKAN MEDIS SESUAI RUJUKAN KONSULTASI",
    informasiLain:
      "RUJUKAN LAB KE FASILITAS KESEHATAN KEDUA UNTUK ANALISIS DARAH DAN URINE",
  },
  {
    id: 3,
    nomorRekamMedis: "90-22-12-80-003",
    jamMasuk: "13:00",
    nama: "Hana Putri",
    penjamin: "Mandiri",
    alamat: "Jl. Anggrek No. 17, Bekasi",
    telepon: "081345678901",
    dokter: "Dr. Rizky Aditya, Sp.KJ",
    departemen: "Poli Psikiatri",
    user: "Admin A",
    userEdit: "Admin D",
    tanggalInput: "2023-12-05",
    tanggalEdit: "2023-12-06",
    kontrak: "BY PHONE: KONSULTASI PERAWATAN PSIKOLOGI LEBIH LANJUT",
    informasiLain: "REKOMENDASI KE KONSULTASI PSIKOLOG UNTUK TINDAKAN LANJUTAN",
  },
  {
    id: 4,
    nomorRekamMedis: "90-22-12-80-004",
    jamMasuk: "09:45",
    nama: "Lina Mariska",
    penjamin: "Pribadi",
    alamat: "Jl. Mawar Blok A No. 4, Jakarta",
    telepon: "081456789012",
    dokter: "Dr. Anita Sari, Sp.KK",
    departemen: "Poli Kulit",
    user: "Admin C",
    userEdit: "Admin A",
    tanggalInput: "2023-11-20",
    tanggalEdit: "2023-11-22",
    kontrak: "KONSULTASI LANGSUNG SESUAI PENJADWALAN PASIEN",
    informasiLain: "PENGARAHAN KE LABORATORIUM UNTUK TES ALERGI LENGKAP",
  },
  {
    id: 5,
    nomorRekamMedis: "90-22-12-80-005",
    jamMasuk: "14:15",
    nama: "Andi Kurniawan",
    penjamin: "BPJS",
    alamat: "Jl. Melati No. 10, Tangerang",
    telepon: "081567890123",
    dokter: "Dr. Bambang Setiawan, Sp.OG",
    departemen: "Poli Kandungan",
    user: "Admin B",
    userEdit: "Admin D",
    tanggalInput: "2023-12-10",
    tanggalEdit: "2023-12-11",
    kontrak: "KONSULTASI KONTROL KANDUNGAN DENGAN ULTRASOUND",
    informasiLain: "RUJUKAN KE LABORATORIUM UNTUK ANALISIS DARAH",
  },
  {
    id: 6,
    nomorRekamMedis: "90-22-12-80-006",
    jamMasuk: "10:00",
    nama: "Rani Pratiwi",
    penjamin: "Mandiri",
    alamat: "Jl. Apel Blok C No. 7, Depok",
    telepon: "081678901234",
    dokter: "Dr. Yoga Pratama, Sp.JP",
    departemen: "Poli Jantung",
    user: "Admin A",
    userEdit: "Admin C",
    tanggalInput: "2023-12-03",
    tanggalEdit: "2023-12-04",
    kontrak: "BY PHONE: TINDAKAN KONTROL PASIEN DENGAN MASALAH JANTUNG",
    informasiLain: "JADWAL TES EKG ULANG DALAM 1 MINGGU",
  },
  {
    id: 7,
    nomorRekamMedis: "90-22-12-80-007",
    jamMasuk: "12:30",
    nama: "Fadilah Nur",
    penjamin: "BPJS",
    alamat: "Jl. Rambutan No. 15, Bogor",
    telepon: "081789012345",
    dokter: "Dr. Lina Hartati, Sp.N",
    departemen: "Poli Saraf",
    user: "Admin D",
    userEdit: "Admin B",
    tanggalInput: "2023-11-30",
    tanggalEdit: "2023-12-01",
    kontrak: "TINDAKAN MEDIS SESUAI RUJUKAN PASIEN KE POLI SARAF",
    informasiLain: "KONSULTASI LANJUTAN KE TERAPIS SARAF",
  },
  {
    id: 8,
    nomorRekamMedis: "90-22-12-80-008",
    jamMasuk: "11:00",
    nama: "Ahmad Faisal",
    penjamin: "Pribadi",
    alamat: "Jl. Anggrek No. 20, Tangerang",
    telepon: "081890123456",
    dokter: "Dr. Maria Yunita, Sp.M",
    departemen: "Poli Mata",
    user: "Admin A",
    userEdit: "Admin C",
    tanggalInput: "2023-12-04",
    tanggalEdit: "2023-12-05",
    kontrak: "KONTROL PASIEN OPERASI KATARAK",
    informasiLain: "TES VISUS DI POLIKLINIK MATA",
  },
];

export const dataRawatJalan = [
  {
    id: 1,
    nomorRekamMedis: "90-22-12-01",
    jamMasuk: "08:00",
    nama: "Arif Budiman",
    penjamin: "BPJS",
    alamat: "Jl. Merdeka No.10, Jakarta",
    telepon: "081234567890",
    dokter: "Dr. Rahmat Pratama, Sp.A",
    departemen: "Poli Anak",
    user: "Admin 1",
    userEdit: "Admin 2",
    tanggalInput: "2024-01-01",
    tanggalEdit: "2024-01-02",
    kontrak: "Rawat Jalan",
    informasiLain: "Pasien baru dengan keluhan demam",
  },
  {
    id: 2,
    nomorRekamMedis: "90-22-12-02",
    jamMasuk: "09:00",
    nama: "Dewi Lestari",
    penjamin: "Prudential",
    alamat: "Jl. Anggrek No.7, Bandung",
    telepon: "081234567891",
    dokter: "Dr. Maria Yunita, Sp.M",
    departemen: "Poli Mata",
    user: "Admin 3",
    userEdit: "Admin 4",
    tanggalInput: "2024-01-01",
    tanggalEdit: "2024-01-02",
    kontrak: "Rawat Jalan",
    informasiLain: "Pemeriksaan mata rutin",
  },
  {
    id: 3,
    nomorRekamMedis: "90-22-12-03",
    jamMasuk: "10:30",
    nama: "Budi Hartono",
    penjamin: "Mandiri",
    alamat: "Jl. Kenanga No.5, Surabaya",
    telepon: "081345678901",
    dokter: "Dr. Indra Wijaya, Sp.PD",
    departemen: "Poli Penyakit Dalam",
    user: "Admin 5",
    userEdit: "Admin 6",
    tanggalInput: "2024-01-03",
    tanggalEdit: "2024-01-04",
    kontrak: "Rawat Jalan",
    informasiLain: "Keluhan sakit perut kronis",
  },
  {
    id: 4,
    nomorRekamMedis: "90-22-12-04",
    jamMasuk: "11:00",
    nama: "Citra Dewi",
    penjamin: "BPJS",
    alamat: "Jl. Melati No.2, Medan",
    telepon: "081456789012",
    dokter: "Dr. Bambang Setiawan, Sp.OG",
    departemen: "Poli Kandungan",
    user: "Admin 7",
    userEdit: "Admin 8",
    tanggalInput: "2024-01-05",
    tanggalEdit: "2024-01-06",
    kontrak: "Rawat Jalan",
    informasiLain: "Pemeriksaan kehamilan trimester kedua",
  },
  {
    id: 5,
    nomorRekamMedis: "90-22-12-05",
    jamMasuk: "13:00",
    nama: "Fadilah Nur",
    penjamin: "BPJS",
    alamat: "Jl. Mawar No.10, Bekasi",
    telepon: "081567890123",
    dokter: "Dr. Susi Yulianti, Sp.THT",
    departemen: "Poli THT",
    user: "Admin 9",
    userEdit: "Admin 10",
    tanggalInput: "2024-01-07",
    tanggalEdit: "2024-01-08",
    kontrak: "Rawat Jalan",
    informasiLain: "Pemeriksaan pendengaran",
  },
  {
    id: 6,
    nomorRekamMedis: "90-22-12-06",
    jamMasuk: "14:00",
    nama: "Lina Mariska",
    penjamin: "Mandiri",
    alamat: "Jl. Jambu No.21, Tangerang",
    telepon: "081678901234",
    dokter: "Dr. Hendro Kusuma, Sp.B",
    departemen: "Poli Bedah",
    user: "Admin 11",
    userEdit: "Admin 12",
    tanggalInput: "2024-01-09",
    tanggalEdit: "2024-01-10",
    kontrak: "Rawat Jalan",
    informasiLain: "Kontrol pascaoperasi",
  },
  {
    id: 7,
    nomorRekamMedis: "90-22-12-07",
    jamMasuk: "15:00",
    nama: "Agus Supriyanto",
    penjamin: "Asuransi",
    alamat: "Jl. Mangga No.4, Depok",
    telepon: "081789012345",
    dokter: "Dr. Rizky Aditya, Sp.KJ",
    departemen: "Poli Psikiatri",
    user: "Admin 13",
    userEdit: "Admin 14",
    tanggalInput: "2024-01-11",
    tanggalEdit: "2024-01-12",
    kontrak: "Rawat Jalan",
    informasiLain: "Konsultasi rutin",
  },
  {
    id: 8,
    nomorRekamMedis: "90-22-12-08",
    jamMasuk: "16:00",
    nama: "Salsa Ayu",
    penjamin: "BPJS",
    alamat: "Jl. Apel No.8, Bogor",
    telepon: "081890123456",
    dokter: "Dr. Anita Sari, Sp.KK",
    departemen: "Poli Kulit",
    user: "Admin 15",
    userEdit: "Admin 16",
    tanggalInput: "2024-01-13",
    tanggalEdit: "2024-01-14",
    kontrak: "Rawat Jalan",
    informasiLain: "Pemeriksaan alergi kulit",
  },
  {
    id: 9,
    nomorRekamMedis: "90-22-12-09",
    jamMasuk: "08:30",
    nama: "Rama Nugraha",
    penjamin: "BPJS",
    alamat: "Jl. Durian No.6, Semarang",
    telepon: "081901234567",
    dokter: "Dr. Yoga Pratama, Sp.JP",
    departemen: "Poli Jantung",
    user: "Admin 17",
    userEdit: "Admin 18",
    tanggalInput: "2024-01-15",
    tanggalEdit: "2024-01-16",
    kontrak: "Rawat Jalan",
    informasiLain: "Kontrol hipertensi",
  },
  {
    id: 10,
    nomorRekamMedis: "90-22-12-10",
    jamMasuk: "09:45",
    nama: "Daffa Pramudya",
    penjamin: "Mandiri",
    alamat: "Jl. Rambutan No.9, Yogyakarta",
    telepon: "082012345678",
    dokter: "Dr. Lina Hartati, Sp.N",
    departemen: "Poli Saraf",
    user: "Admin 19",
    userEdit: "Admin 20",
    tanggalInput: "2024-01-17",
    tanggalEdit: "2024-01-18",
    kontrak: "Rawat Jalan",
    informasiLain: "Keluhan migrain kronis",
  },
];

export const dataRawatInap = [
  {
    id: 1,
    nomorRekamMedis: "90-22-12-01",
    tanggalWaw: "09 Des 2024",
    tanggalMasuk: "09 Des 2024",
    nama: "Dr. Damar Mahendra",
    telepon: "08112345678",
    diagnosis:
      "HIBERNOMA TUMOR BENIG. TINDAKAN UNTUK MENDAFTAR KONTROL KE RADIOLOGY ACE ASSURANCE LAPOR KE DOKTER SPESIALIS",
    dokter: "Teguh Pratama, Sp.B",
    kelas: "Kelas 1",
    kontrak: "By phone request asuransi 1x",
    user: "Siti Nurhayati",
    tanggalInput: "08 Des 2024",
    tanggalEdit: "08 Des 2024",
    informasiLain: "Fee RCV1 Asuransi",
  },
  {
    id: 2,
    nomorRekamMedis: "90-22-12-02",
    tanggalWaw: "08 Des 2024",
    tanggalMasuk: "08 Des 2024",
    nama: "Susanna Dewi",
    telepon: "08117891234",
    diagnosis:
      "MULTIPLE TUMORS MAMAE EVALUATED. LAB FOR BIOPSI PENDING UNTIL FINAL CHECK WITH SPESIALIS",
    dokter: "Farid Santoso, Sp.Rad",
    kelas: "VIP",
    kontrak: "Permintaan asuransi 2x",
    user: "Agus Harianto",
    tanggalInput: "07 Des 2024",
    tanggalEdit: "07 Des 2024",
    informasiLain: "Logistik update untuk farmasi.",
  },
  {
    id: 3,
    nomorRekamMedis: "90-22-12-03",
    tanggalWaw: "08 Des 2024",
    tanggalMasuk: "08 Des 2024",
    nama: "Betty Winata",
    telepon: "08117891321",
    diagnosis: "3 TUMORS HEPATOCYTE SUPER MULTIPLE UNCONFIRMED",
    dokter: "Dr. Satriyo",
    kelas: "Kelas 2",
    kontrak: "Rujukan final insurance",
    user: "User Asuransi Admin",
    tanggalInput: "07 Des 2024",
    tanggalEdit: "08 Des 2024",
    informasiLain: "Critical Logistic update.",
  },
  {
    id: 4,
    nomorRekamMedis: "90-22-12-04",
    tanggalWaw: "07 Des 2024",
    tanggalMasuk: "06 Des 2024",
    nama: "Annisa Putri",
    telepon: "08123456789",
    diagnosis: "ULTRASONIC PNEUMONIA DIAGNOSIS UNCLEAR",
    dokter: "Dr. Pras",
    kelas: "VIP",
    kontrak: "Kontrol final klinis",
    user: "Nur Hamida",
    tanggalInput: "06 Des 2024",
    tanggalEdit: "07 Des 2024",
    informasiLain: "Final Checking.",
  },
  {
    id: 5,
    nomorRekamMedis: "90-22-12-05",
    tanggalWaw: "07 Des 2024",
    tanggalMasuk: "06 Des 2024",
    nama: "Lina Kusuma",
    telepon: "08134567890",
    diagnosis: "LUNG FIBROSIS FULL CHECK",
    dokter: "Dr. Nina Sartika",
    kelas: "Kelas 1",
    kontrak: "Rujukan kontrol",
    user: "Wahyu Hartanto",
    tanggalInput: "05 Des 2024",
    tanggalEdit: "06 Des 2024",
    informasiLain: "Farmasi logistik perlu",
  },
  {
    id: 6,
    nomorRekamMedis: "90-22-12-06",
    tanggalWaw: "07 Des 2024",
    tanggalMasuk: "05 Des 2024",
    nama: "Rendy Wijaya",
    telepon: "08145678912",
    diagnosis: "BENIGN LUMBAR DETAILED STUDY",
    dokter: "Dr. Fadhil",
    kelas: "Kelas 3",
    kontrak: "Rawat inap",
    user: "Indah Yusnita",
    tanggalInput: "04 Des 2024",
    tanggalEdit: "05 Des 2024",
    informasiLain: "Updated insurance documents",
  },
  {
    id: 7,
    nomorRekamMedis: "90-22-12-07",
    tanggalWaw: "06 Des 2024",
    tanggalMasuk: "05 Des 2024",
    nama: "Faris Nugraha",
    telepon: "08156789123",
    diagnosis: "PANCREATIC MALIGNANCY CHECK SCHEDULED",
    dokter: "Dr. Bayu Satria",
    kelas: "Kelas 1",
    kontrak: "Konsultasi",
    user: "Amalia Putri",
    tanggalInput: "04 Des 2024",
    tanggalEdit: "05 Des 2024",
    informasiLain: "Insurance final confirmation pending.",
  },
  {
    id: 8,
    nomorRekamMedis: "90-22-12-08",
    tanggalWaw: "06 Des 2024",
    tanggalMasuk: "05 Des 2024",
    nama: "Aditya Saputra",
    telepon: "08167891234",
    diagnosis: "INFECTION CRITICAL IN FOLLOW-UP",
    dokter: "Dr. Siti Munawaroh",
    kelas: "VIP",
    kontrak: "Post-test follow-up",
    user: "Dewi Karunia",
    tanggalInput: "03 Des 2024",
    tanggalEdit: "04 Des 2024",
    informasiLain: "Updated farmasi pengobatan.",
  },
  {
    id: 9,
    nomorRekamMedis: "90-22-12-09",
    tanggalWaw: "05 Des 2024",
    tanggalMasuk: "04 Des 2024",
    nama: "Viona Anindya",
    telepon: "08178912345",
    diagnosis: "CARDIAC DISFUNCTION AND CONSULT",
    dokter: "Dr. Teguh Wahyudi",
    kelas: "Kelas 1",
    kontrak: "Full consultation",
    user: "Deny Susanto",
    tanggalInput: "03 Des 2024",
    tanggalEdit: "04 Des 2024",
    informasiLain: "Finalizing asuransi admin",
  },
  {
    id: 10,
    nomorRekamMedis: "90-22-12-10",
    tanggalWaw: "05 Des 2024",
    tanggalMasuk: "04 Des 2024",
    nama: "Hendra Mahardika",
    telepon: "08189123456",
    diagnosis: "MUSCLE FRACTURE PAIN SCHEDULE",
    dokter: "Dr. Faisal Hanif",
    kelas: "Kelas 2",
    kontrak: "Insurance scheduled next",
    user: "Tari Kartini",
    tanggalInput: "03 Des 2024",
    tanggalEdit: "04 Des 2024",
    informasiLain: "Updated logistics.",
  },
];

export const dataPerjanjianOperasi = [
  {
    id: 1,
    ruangOperasi: "RO-101",
    noRegistrasi: "2023120001",
    tanggalOperasi: "09 Des 2024",
    jamOperasi: "08:00 - 10:00",
    pasien: "Damar Mahendra",
    noHP: "08123456789",
    sex: "L",
    kelas: "Kelas 1",
    diagnosis: "Hernia Inguinalis",
    tindakan: "Herniotomi",
    keterangan: "Pasien perlu rawat inap setelah operasi",
    operator: "Dr. Teguh Pratama, Sp.B",
    tipeAnestesi: "Umum",
    jaminan: "BPJS",
    user: "Admin Operasi",
    userEdit: "Siti Rahmawati",
    tanggalInput: "08 Des 2024",
    tanggalEdit: "09 Des 2024",
  },
  {
    id: 2,
    ruangOperasi: "RO-102",
    noRegistrasi: "2023120002",
    tanggalOperasi: "09 Des 2024",
    jamOperasi: "10:30 - 12:30",
    pasien: "Susanna Dewi",
    noHP: "08134567890",
    sex: "P",
    kelas: "VIP",
    diagnosis: "Cholelithiasis",
    tindakan: "Kolesistektomi",
    keterangan: "Pasien dalam pengawasan pascaoperasi",
    operator: "Dr. Farid Santoso, Sp.Rad",
    tipeAnestesi: "Lokal",
    jaminan: "Mandiri",
    user: "Admin Operasi",
    userEdit: "Rina Kusuma",
    tanggalInput: "08 Des 2024",
    tanggalEdit: "09 Des 2024",
  },
  {
    id: 3,
    ruangOperasi: "RO-103",
    noRegistrasi: "2023120003",
    tanggalOperasi: "10 Des 2024",
    jamOperasi: "09:00 - 11:00",
    pasien: "Betty Winata",
    noHP: "08145678901",
    sex: "P",
    kelas: "Kelas 2",
    diagnosis: "Appendicitis Akut",
    tindakan: "Appendektomi",
    keterangan: "Pemantauan 24 jam pascaoperasi",
    operator: "Dr. Satriyo, Sp.B",
    tipeAnestesi: "Umum",
    jaminan: "Asuransi",
    user: "Admin Operasi",
    userEdit: "Agus Harianto",
    tanggalInput: "09 Des 2024",
    tanggalEdit: "10 Des 2024",
  },
  {
    id: 4,
    ruangOperasi: "RO-104",
    noRegistrasi: "2023120004",
    tanggalOperasi: "10 Des 2024",
    jamOperasi: "13:00 - 15:00",
    pasien: "Annisa Putri",
    noHP: "08156789012",
    sex: "P",
    kelas: "VIP",
    diagnosis: "Tumor Payudara",
    tindakan: "Lumpektomi",
    keterangan: "Histopatologi pascaoperasi",
    operator: "Dr. Pras, Sp.B",
    tipeAnestesi: "Umum",
    jaminan: "BPJS",
    user: "Admin Operasi",
    userEdit: "Hendra Wijaya",
    tanggalInput: "09 Des 2024",
    tanggalEdit: "10 Des 2024",
  },
  {
    id: 5,
    ruangOperasi: "RO-105",
    noRegistrasi: "2023120005",
    tanggalOperasi: "11 Des 2024",
    jamOperasi: "08:00 - 10:00",
    pasien: "Rendy Wijaya",
    noHP: "08167890123",
    sex: "L",
    kelas: "Kelas 1",
    diagnosis: "Fraktur Tibia",
    tindakan: "ORIF (Open Reduction Internal Fixation)",
    keterangan: "Pasien akan menjalani fisioterapi",
    operator: "Dr. Nina Sartika, Sp.OT",
    tipeAnestesi: "Umum",
    jaminan: "Mandiri",
    user: "Admin Operasi",
    userEdit: "Dewi Karunia",
    tanggalInput: "10 Des 2024",
    tanggalEdit: "11 Des 2024",
  },
  {
    id: 6,
    ruangOperasi: "RO-106",
    noRegistrasi: "2023120006",
    tanggalOperasi: "11 Des 2024",
    jamOperasi: "10:30 - 12:30",
    pasien: "Faris Nugraha",
    noHP: "08178901234",
    sex: "L",
    kelas: "Kelas 3",
    diagnosis: "Cataract",
    tindakan: "Phacoemulsifikasi",
    keterangan: "Pasien kontrol ulang 1 minggu",
    operator: "Dr. Bayu Satria, Sp.M",
    tipeAnestesi: "Lokal",
    jaminan: "BPJS",
    user: "Admin Operasi",
    userEdit: "Rina Kusuma",
    tanggalInput: "10 Des 2024",
    tanggalEdit: "11 Des 2024",
  },
  {
    id: 7,
    ruangOperasi: "RO-107",
    noRegistrasi: "2023120007",
    tanggalOperasi: "12 Des 2024",
    jamOperasi: "09:00 - 11:00",
    pasien: "Aditya Saputra",
    noHP: "08189012345",
    sex: "L",
    kelas: "VIP",
    diagnosis: "Varises",
    tindakan: "Stripping",
    keterangan: "Rawat jalan pascaoperasi",
    operator: "Dr. Siti Munawaroh, Sp.B",
    tipeAnestesi: "Lokal",
    jaminan: "Asuransi",
    user: "Admin Operasi",
    userEdit: "Wahyu Hartanto",
    tanggalInput: "11 Des 2024",
    tanggalEdit: "12 Des 2024",
  },
  {
    id: 8,
    ruangOperasi: "RO-108",
    noRegistrasi: "2023120008",
    tanggalOperasi: "12 Des 2024",
    jamOperasi: "13:00 - 15:00",
    pasien: "Viona Anindya",
    noHP: "08190123456",
    sex: "P",
    kelas: "Kelas 1",
    diagnosis: "Hernia Umbilikalis",
    tindakan: "Herniorafi",
    keterangan: "Kontrol ulang 2 minggu",
    operator: "Dr. Teguh Wahyudi, Sp.B",
    tipeAnestesi: "Umum",
    jaminan: "Mandiri",
    user: "Admin Operasi",
    userEdit: "Hendra Wijaya",
    tanggalInput: "11 Des 2024",
    tanggalEdit: "12 Des 2024",
  },
  {
    id: 9,
    ruangOperasi: "RO-109",
    noRegistrasi: "2023120009",
    tanggalOperasi: "13 Des 2024",
    jamOperasi: "08:00 - 10:00",
    pasien: "Hendra Mahardika",
    noHP: "08201234567",
    sex: "L",
    kelas: "Kelas 2",
    diagnosis: "Ganglion Cyst",
    tindakan: "Eksisi",
    keterangan: "Tidak ada komplikasi",
    operator: "Dr. Faisal Hanif, Sp.OT",
    tipeAnestesi: "Lokal",
    jaminan: "BPJS",
    user: "Admin Operasi",
    userEdit: "Agus Harianto",
    tanggalInput: "12 Des 2024",
    tanggalEdit: "13 Des 2024",
  },
  {
    id: 10,
    ruangOperasi: "RO-110",
    noRegistrasi: "2023120010",
    tanggalOperasi: "13 Des 2024",
    jamOperasi: "10:30 - 12:30",
    pasien: "Lina Kusuma",
    noHP: "08212345678",
    sex: "P",
    kelas: "Kelas 3",
    diagnosis: "Tonsillitis Kronis",
    tindakan: "Tonsilektomi",
    keterangan: "Pasien pulang pada hari yang sama",
    operator: "Dr. Nina Sartika, Sp.THT",
    tipeAnestesi: "Lokal",
    jaminan: "Mandiri",
    user: "Admin Operasi",
    userEdit: "Siti Rahmawati",
    tanggalInput: "12 Des 2024",
    tanggalEdit: "13 Des 2024",
  },
];
