export const pasienBayi = [
  {
    id: 1,
    value: "VVIP",
    noRekamMedis: "13212312",
    label: "VVIP",
    ruang: "VVIP 101",
    NoTempatTidur: "412",
    namaBayi: `FATIMAH ZAHRO`,
    dokter: "maya munigar apandi spjp.dr",
    namaKeluarga: "bahagia",
  },
  {
    id: 2,
    value: "Kelas 1",
    noRekamMedis: "99212314",
    ruang: "Kelas 1 105",
    label: "Kelas 1",
    NoTempatTidur: "327",
    namaBayi: `ANNA RINA FRiYANTI`,
    dokter: "Kencana shinta Moser,SpOG,dr",
    namaKeluarga: "cemara",
  },
  {
    id: 3,
    value: "ISOLASI",
    noRekamMedis: "87357123",
    ruang: "ISOLASI 104",
    label: "ISOLASI",
    NoTempatTidur: "817",
    namaBayi: "VIRA HANDAYANI",
    dokter: "Yuhana Fitra,Sp.PD.dr",
    namaKeluarga: "sehat terus",
  },
  {
    id: 4,
    value: "VIP",
    noRekamMedis: "76324567",
    ruang: "VIP 202",
    label: "VIP",
    NoTempatTidur: "512",
    namaBayi: "MUHAMMAD ALI",
    dokter: "Irma Lestari,SpA.dr",
    namaKeluarga: "harmoni",
  },
  {
    id: 5,
    value: "Kelas 2",
    noRekamMedis: "34897562",
    ruang: "Kelas 2 301",
    label: "Kelas 2",
    NoTempatTidur: "231",
    namaBayi: "ZAHRA AMELIA",
    dokter: "Putri Saraswati,Sp.KK.dr",
    namaKeluarga: "ceria",
  },
  {
    id: 6,
    value: "Kelas 3",
    noRekamMedis: "49876512",
    ruang: "Kelas 3 401",
    label: "Kelas 3",
    NoTempatTidur: "612",
    namaBayi: "NURUL HUDA",
    dokter: "Aldino Pramudya,Sp.JP.dr",
    namaKeluarga: "purnama",
  },
  {
    id: 7,
    value: "VVIP",
    noRekamMedis: "67834523",
    ruang: "VVIP 103",
    label: "VVIP",
    NoTempatTidur: "456",
    namaBayi: "RAFI AKBAR",
    dokter: "Citra Dewi,Sp.A.dr",
    namaKeluarga: "sejahtera",
  },
  {
    id: 8,
    value: "Kelas 1",
    noRekamMedis: "98234567",
    ruang: "Kelas 1 107",
    label: "Kelas 1",
    NoTempatTidur: "317",
    namaBayi: "LATHIFA NUR",
    dokter: "Erika Sari,Sp.KFR.dr",
    namaKeluarga: "harmonis",
  },
  {
    id: 9,
    value: "ISOLASI",
    noRekamMedis: "87234521",
    ruang: "ISOLASI 108",
    label: "ISOLASI",
    NoTempatTidur: "814",
    namaBayi: "DARA CINTA",
    dokter: "Fauzan Arif,Sp.PD.dr",
    namaKeluarga: "indah",
  },
  {
    id: 10,
    value: "VIP",
    noRekamMedis: "12478635",
    ruang: "VIP 203",
    label: "VIP",
    NoTempatTidur: "563",
    namaBayi: "REHAN MAHARDIKA",
    dokter: "Galih Putra,Sp.A.dr",
    namaKeluarga: "bahagia",
  },
  {
    id: 11,
    value: "Kelas 2",
    noRekamMedis: "56389214",
    ruang: "Kelas 2 302",
    label: "Kelas 2",
    NoTempatTidur: "238",
    namaBayi: "ANISA KAMILA",
    dokter: "Hendra Wijaya,Sp.THT.dr",
    namaKeluarga: "sakura",
  },
  {
    id: 12,
    value: "Kelas 3",
    noRekamMedis: "89234561",
    ruang: "Kelas 3 402",
    label: "Kelas 3",
    NoTempatTidur: "619",
    namaBayi: "YUSUF FAHMI",
    dokter: "Ika Ramadani,Sp.A.dr",
    namaKeluarga: "cerah",
  },
  {
    id: 13,
    value: "VVIP",
    noRekamMedis: "12984567",
    ruang: "VVIP 105",
    label: "VVIP",
    NoTempatTidur: "414",
    namaBayi: "KEVIN PRASETYO",
    dokter: "Jasmine Putri,Sp.KK.dr",
    namaKeluarga: "indah",
  },
  {
    id: 14,
    value: "Kelas 1",
    noRekamMedis: "98236587",
    ruang: "Kelas 1 109",
    label: "Kelas 1",
    NoTempatTidur: "325",
    namaBayi: "NADIA SAFIRA",
    dokter: "Kirana Anggara,Sp.A.dr",
    namaKeluarga: "harmoni",
  },
  {
    id: 15,
    value: "ISOLASI",
    noRekamMedis: "87634259",
    ruang: "ISOLASI 110",
    label: "ISOLASI",
    NoTempatTidur: "822",
    namaBayi: "DAFFA RAIHAN",
    dokter: "Lestari Widya,Sp.PD.dr",
    namaKeluarga: "bahagia",
  },
  {
    id: 16,
    value: "VIP",
    noRekamMedis: "78324681",
    ruang: "VIP 204",
    label: "VIP",
    NoTempatTidur: "574",
    namaBayi: "MIRA ANDINI",
    dokter: "Maya Susanti,Sp.A.dr",
    namaKeluarga: "ceria",
  },
  {
    id: 17,
    value: "Kelas 2",
    noRekamMedis: "67389542",
    ruang: "Kelas 2 303",
    label: "Kelas 2",
    NoTempatTidur: "241",
    namaBayi: "FIKRI NURHALIZA",
    dokter: "Nina Ratnasari,Sp.KK.dr",
    namaKeluarga: "purnama",
  },
  {
    id: 18,
    value: "Kelas 3",
    noRekamMedis: "98764321",
    ruang: "Kelas 3 403",
    label: "Kelas 3",
    NoTempatTidur: "625",
    namaBayi: "ALYA HUSNA",
    dokter: "Omar Rizky,Sp.A.dr",
    namaKeluarga: "sehat",
  },
  {
    id: 19,
    value: "VVIP",
    noRekamMedis: "34567281",
    ruang: "VVIP 106",
    label: "VVIP",
    NoTempatTidur: "418",
    namaBayi: "ZAID ALFARISI",
    dokter: "Putri Maharani,Sp.A.dr",
    namaKeluarga: "indah",
  },
  {
    id: 20,
    value: "Kelas 1",
    noRekamMedis: "56378492",
    ruang: "Kelas 1 111",
    label: "Kelas 1",
    NoTempatTidur: "329",
    namaBayi: "KARINA WIDIYA",
    dokter: "Qiana Arsyad,Sp.A.dr",
    namaKeluarga: "cemara",
  },
];

export const pasienLama = [
  {
    noRm: "12-22-83-99",
    oldRm: "00-77-08-90",
    nama: "Anisa Sahrini",
    alamat: "Pondok Lakah Permai blok EE",
    tempatTanggalLahir: "Jakarta, 01 Jan 2010",
  },
  {
    noRm: "13-23-84-01",
    oldRm: "01-78-09-91",
    nama: "Budi Santoso",
    alamat: "Jalan Mawar No. 12",
    tempatTanggalLahir: "Bandung, 15 Feb 1998",
  },
  {
    noRm: "14-24-85-02",
    oldRm: "02-79-10-92",
    nama: "Citra Maharani",
    alamat: "Komp. Griya Harmoni Blok A1",
    tempatTanggalLahir: "Surabaya, 20 Mar 2005",
  },
  {
    noRm: "15-25-86-03",
    oldRm: "03-80-11-93",
    nama: "Dian Pratama",
    alamat: "Jl. Pelajar Pejuang 45 No. 8",
    tempatTanggalLahir: "Medan, 05 Apr 2000",
  },
  {
    noRm: "16-26-87-04",
    oldRm: "04-81-12-94",
    nama: "Eka Firmansyah",
    alamat: "Jl. Cendana Blok C2",
    tempatTanggalLahir: "Yogyakarta, 10 Mei 1995",
  },
  {
    noRm: "17-27-88-05",
    oldRm: "05-82-01-95",
    nama: "Fahmi Setiawan",
    alamat: "Jl. Anggrek No. 15",
    tempatTanggalLahir: "Semarang, 25 Jun 1990",
  },
  {
    noRm: "18-28-89-06",
    oldRm: "06-83-02-96",
    nama: "Gita Ramadhani",
    alamat: "Perumahan Taman Sari Blok B4",
    tempatTanggalLahir: "Makassar, 12 Jul 2003",
  },
  {
    noRm: "19-29-90-07",
    oldRm: "07-84-03-97",
    nama: "Hendra Wijaya",
    alamat: "Jl. Melati Blok D3",
    tempatTanggalLahir: "Palembang, 30 Agu 1987",
  },
  {
    noRm: "20-30-91-08",
    oldRm: "08-85-04-98",
    nama: "Indra Lesmana",
    alamat: "Jl. Kenanga No. 7",
    tempatTanggalLahir: "Balikpapan, 18 Sep 1992",
  },
  {
    noRm: "21-31-92-09",
    oldRm: "09-86-05-99",
    nama: "Joko Prayitno",
    alamat: "Jl. Cemara Blok F1",
    tempatTanggalLahir: "Solo, 01 Okt 1999",
  },
  {
    noRm: "22-32-93-10",
    oldRm: "10-87-06-00",
    nama: "Kartika Dewi",
    alamat: "Jl. Flamboyan No. 4",
    tempatTanggalLahir: "Bogor, 15 Nov 1996",
  },
  {
    noRm: "23-33-94-11",
    oldRm: "11-88-07-01",
    nama: "Lestari Anindya",
    alamat: "Jl. Durian Blok E5",
    tempatTanggalLahir: "Denpasar, 27 Des 2001",
  },
  {
    noRm: "24-34-95-12",
    oldRm: "12-89-08-02",
    nama: "Mulyadi",
    alamat: "Jl. Rambutan Blok G3",
    tempatTanggalLahir: "Pekanbaru, 03 Jan 1989",
  },
  {
    noRm: "25-35-96-13",
    oldRm: "13-90-09-03",
    nama: "Nur Azizah",
    alamat: "Jl. Pisang No. 10",
    tempatTanggalLahir: "Pontianak, 20 Feb 1997",
  },
  {
    noRm: "26-36-97-14",
    oldRm: "14-91-10-04",
    nama: "Omar Alfarizi",
    alamat: "Jl. Mangga Blok H4",
    tempatTanggalLahir: "Malang, 11 Mar 1994",
  },
];
