export const jadwalDokterByDate = {
  "2025-01-09": [
    {
      id: 1,
      label: "Dr. John Doe",
      department: "Cardiology",
      waktuPraktek: "10:00 - 19:00",
      noUrut: 1,
    },
    {
      id: 2,
      label: "Dr. Jane Smith",
      department: "Neurology",
      waktuPraktek: "09:00 - 17:00",
      noUrut: 2,
    },
    {
      id: 5,
      label: "Dr. Eric Taylor",
      department: "Orthopedics",
      waktuPraktek: "08:00 - 16:00",
      noUrut: 3,
    },
    {
      id: 6,
      label: "Dr. Nancy Drew",
      department: "Dermatology",
      waktuPraktek: "13:00 - 20:00",
      noUrut: 4,
    },
    {
      id: 7,
      label: "Dr. Lisa Cuddy",
      department: "General Medicine",
      waktuPraktek: "11:00 - 18:00",
      noUrut: 5,
    },
  ],
  "2025-01-10": [
    {
      id: 3,
      label: "Dr. Alice Brown",
      department: "Pediatrics",
      waktuPraktek: "08:00 - 14:00",
      noUrut: 1,
    },
    {
      id: 4,
      label: "Dr. Xavier Adams",
      department: "General Surgery",
      waktuPraktek: "14:00 - 20:00",
      noUrut: 2,
    },
    {
      id: 8,
      label: "Dr. Omar Little",
      department: "Psychiatry",
      waktuPraktek: "12:00 - 19:00",
      noUrut: 3,
    },
    {
      id: 9,
      label: "Dr. Gregory House",
      department: "Nephrology",
      waktuPraktek: "07:00 - 15:00",
      noUrut: 4,
    },
    {
      id: 10,
      label: "Dr. Meredith Grey",
      department: "Surgery",
      waktuPraktek: "10:00 - 18:00",
      noUrut: 5,
    },
  ],
  "2025-01-11": [
    {
      id: 11,
      label: "Dr. Derek Shepherd",
      department: "Neurosurgery",
      waktuPraktek: "09:00 - 17:00",
      noUrut: 1,
    },
    {
      id: 12,
      label: "Dr. Christina Yang",
      department: "Cardiothoracic Surgery",
      waktuPraktek: "08:00 - 16:00",
      noUrut: 2,
    },
    {
      id: 13,
      label: "Dr. George O'Malley",
      department: "Trauma Surgery",
      waktuPraktek: "14:00 - 22:00",
      noUrut: 3,
    },
    {
      id: 14,
      label: "Dr. Izzie Stevens",
      department: "Oncology",
      waktuPraktek: "07:00 - 15:00",
      noUrut: 4,
    },
    {
      id: 15,
      label: "Dr. Alex Karev",
      department: "Pediatric Surgery",
      waktuPraktek: "13:00 - 21:00",
      noUrut: 5,
    },
  ],
};
