export const dataTindakanOperasi = [
  {
    id: 1,
    namaTindakan: "APENDIKTOMI LAPAROSKOPI",
    teknikOperasi: "LAP",
    jenisOperasi: "BESAR (DEWASA)",
  },
  {
    id: 2,
    namaTindakan: "APENDIKTOMI LAPAROTOMI",
    teknikOperasi: "LAP",
    jenisOperasi: "BESAR (DEWASA)",
  },
  {
    id: 3,
    namaTindakan: "KLISIS 15 CM (RUJUK)",
    teknikOperasi: "COTHAK",
    jenisOperasi: "COTHAK",
  },
  {
    id: 4,
    namaTindakan: "KLISIS 10 CM (DEWASA)",
    teknikOperasi: "COTHAK",
    jenisOperasi: "COTHAK",
  },
  {
    id: 5,
    namaTindakan: "KLISIS NONSENSICAL SIMPLE",
    teknikOperasi: "BATA",
    jenisOperasi: "SEDANG",
  },
  {
    id: 6,
    namaTindakan: "ASESIS ATERIA ANGKAT TUMOR ABNORMAL",
    teknikOperasi: "MEGA DISSEKSI",
    jenisOperasi: "VONULLER",
  },
  {
    id: 7,
    namaTindakan: "ASESIS KISTA",
    teknikOperasi: "ONALOG",
    jenisOperasi: "ONALOG",
  },
  {
    id: 8,
    namaTindakan: "ASESIS DARAH",
    teknikOperasi: "HIDROLOG",
    jenisOperasi: "HIDROLOG",
  },
  {
    id: 9,
    namaTindakan: "ASESIS KISTA SIMPLE (KUTIBAN SEBAR)",
    teknikOperasi: "BESAR TULANG (OPTIMAL)",
    jenisOperasi: "BESAR TULANG (OPTIMAL)",
  },
  {
    id: 10,
    namaTindakan: "ASESIS DARAH KISTA MEDIUM (3D)",
    teknikOperasi: "BESAR TULANG (OPTIMAL)",
    jenisOperasi: "BESAR TULANG (OPTIMAL)",
  },
  {
    id: 11,
    namaTindakan: "MAPUNG TANGGAP DARAH DUNIA",
    teknikOperasi: "VONULLER",
    jenisOperasi: "VONULLER",
  },
  {
    id: 12,
    namaTindakan: "MAPUNG DARAH DAN EKOSISTEM HASIL VONULLER DUNIA MINIMAL",
    teknikOperasi: "VONULLER",
    jenisOperasi: "VONULLER",
  },
  {
    id: 13,
    namaTindakan: "MAPUNG DARAH HASIL KUTUB MINIMAL",
    teknikOperasi: "VONULLER",
    jenisOperasi: "VONULLER",
  },
  {
    id: 14,
    namaTindakan: "MAPUNG DARAH HASIL KUTUB BESAR",
    teknikOperasi: "VONULLER",
    jenisOperasi: "VONULLER",
  },
];

export const jenisOperasi = [
  { label: "Bedah", value: "bedah" },
  { label: "Bedah Digestive", value: "bedah_digestive" },
  { label: "Bedah Tulang (Ortophedi)", value: "bedah_tulang_ortophedi" },
  { label: "Gigi dan Bedah Mulut", value: "gigi_bedah_mulut" },
  { label: "Mata", value: "mata" },
  { label: "Obsgyn", value: "obsgyn" },
  { label: "Onkologi", value: "onkologi" },
  { label: "Plastik", value: "plastik" },
  { label: "Syaraf", value: "syaraf" },
  { label: "THT", value: "tht" },
  { label: "Urologi", value: "urologi" },
  { label: "Vaskuler", value: "vaskuler" },
  { label: "Operasi", value: "operasi" },
  { label: "Hepatologi", value: "hepatologi" },
  { label: "Bedah ODC", value: "bedah_odc" },
  { label: "Obsgyn ODC", value: "obsgyn_odc" },
  { label: "Endoskopi", value: "endoskopi" },
  { label: "Cathlab", value: "cathlab" },
  { label: "Thorax", value: "thorax" },
  { label: "Bedah Anak", value: "bedah_anak" },
];

export const kategoriOperasi = [
  { label: "OT I", value: "ot_i" },
  { label: "OT II", value: "ot_ii" },
  { label: "OT III", value: "ot_iii" },
  { label: "OT IV", value: "ot_iv" },
  { label: "OT V", value: "ot_v" },
  { label: "Darurat", value: "darurat" },
  { label: "Elektif", value: "elektif" },
  { label: "Minor", value: "minor" },
  { label: "Mayor", value: "mayor" },
  { label: "Khusus", value: "khusus" },
  { label: "Eksplorasi", value: "eksplorasi" },
];
