export const dataTindakanOperasi = [
  {
    id: 1,
    namaTindakan: "APENDIKTOMI LAPAROSKOPI",
    teknikOperasi: "LAP",
    jenisOperasi: "BESAR (DEWASA)",
  },
  {
    id: 2,
    namaTindakan: "APENDIKTOMI LAPAROTOMI",
    teknikOperasi: "LAP",
    jenisOperasi: "BESAR (DEWASA)",
  },
  {
    id: 3,
    namaTindakan: "KLISIS 15 CM (RUJUK)",
    teknikOperasi: "COTHAK",
    jenisOperasi: "COTHAK",
  },
  {
    id: 4,
    namaTindakan: "KLISIS 10 CM (DEWASA)",
    teknikOperasi: "COTHAK",
    jenisOperasi: "COTHAK",
  },
  {
    id: 5,
    namaTindakan: "KLISIS NONSENSICAL SIMPLE",
    teknikOperasi: "BATA",
    jenisOperasi: "SEDANG",
  },
  {
    id: 6,
    namaTindakan: "ASESIS ATERIA ANGKAT TUMOR ABNORMAL",
    teknikOperasi: "MEGA DISSEKSI",
    jenisOperasi: "VONULLER",
  },
  {
    id: 7,
    namaTindakan: "ASESIS KISTA",
    teknikOperasi: "ONALOG",
    jenisOperasi: "ONALOG",
  },
  {
    id: 8,
    namaTindakan: "ASESIS DARAH",
    teknikOperasi: "HIDROLOG",
    jenisOperasi: "HIDROLOG",
  },
  {
    id: 9,
    namaTindakan: "ASESIS KISTA SIMPLE (KUTIBAN SEBAR)",
    teknikOperasi: "BESAR TULANG (OPTIMAL)",
    jenisOperasi: "BESAR TULANG (OPTIMAL)",
  },
  {
    id: 10,
    namaTindakan: "ASESIS DARAH KISTA MEDIUM (3D)",
    teknikOperasi: "BESAR TULANG (OPTIMAL)",
    jenisOperasi: "BESAR TULANG (OPTIMAL)",
  },
  {
    id: 11,
    namaTindakan: "MAPUNG TANGGAP DARAH DUNIA",
    teknikOperasi: "VONULLER",
    jenisOperasi: "VONULLER",
  },
  {
    id: 12,
    namaTindakan: "MAPUNG DARAH DAN EKOSISTEM HASIL VONULLER DUNIA MINIMAL",
    teknikOperasi: "VONULLER",
    jenisOperasi: "VONULLER",
  },
  {
    id: 13,
    namaTindakan: "MAPUNG DARAH HASIL KUTUB MINIMAL",
    teknikOperasi: "VONULLER",
    jenisOperasi: "VONULLER",
  },
  {
    id: 14,
    namaTindakan: "MAPUNG DARAH HASIL KUTUB BESAR",
    teknikOperasi: "VONULLER",
    jenisOperasi: "VONULLER",
  },
];

export const jenisOperasi = [
  { label: "Bedah", value: "bedah" },
  { label: "Bedah Digestive", value: "bedah_digestive" },
  { label: "Bedah Tulang (Ortophedi)", value: "bedah_tulang_ortophedi" },
  { label: "Gigi dan Bedah Mulut", value: "gigi_bedah_mulut" },
  { label: "Mata", value: "mata" },
  { label: "Obsgyn", value: "obsgyn" },
  { label: "Onkologi", value: "onkologi" },
  { label: "Plastik", value: "plastik" },
  { label: "Syaraf", value: "syaraf" },
  { label: "THT", value: "tht" },
  { label: "Urologi", value: "urologi" },
  { label: "Vaskuler", value: "vaskuler" },
  { label: "Operasi", value: "operasi" },
  { label: "Hepatologi", value: "hepatologi" },
  { label: "Bedah ODC", value: "bedah_odc" },
  { label: "Obsgyn ODC", value: "obsgyn_odc" },
  { label: "Endoskopi", value: "endoskopi" },
  { label: "Cathlab", value: "cathlab" },
  { label: "Thorax", value: "thorax" },
  { label: "Bedah Anak", value: "bedah_anak" },
];

export const kategoriOperasi = [
  { label: "OT I", value: "ot_i" },
  { label: "OT II", value: "ot_ii" },
  { label: "OT III", value: "ot_iii" },
  { label: "OT IV", value: "ot_iv" },
  { label: "OT V", value: "ot_v" },
  { label: "Darurat", value: "darurat" },
  { label: "Elektif", value: "elektif" },
  { label: "Minor", value: "minor" },
  { label: "Mayor", value: "mayor" },
  { label: "Khusus", value: "khusus" },
  { label: "Eksplorasi", value: "eksplorasi" },
];

export const ManajemenDepartemen = [
  {
    id: 1,
    namaDepartemen: "Departemen Kardiologi",
    penanggungJawab: "Dr. Andi Setiawan",
    jamOperasional: "08:00 - 17:00",
    ruangan: "Gedung A, Lantai 2",
    lineTelp: "021-1234567",
    tanggalPembuatan: "2025-01-01",
    deskripsi:
      "Departemen yang menangani masalah kesehatan jantung dan pembuluh darah.",
  },
  {
    id: 2,
    namaDepartemen: "Departemen Pediatri",
    penanggungJawab: "Dr. Maria Yunita",
    jamOperasional: "08:00 - 16:00",
    ruangan: "Gedung B, Lantai 3",
    lineTelp: "021-7654321",
    tanggalPembuatan: "2025-01-02",
    deskripsi: "Departemen yang berfokus pada kesehatan anak dan remaja.",
  },
  {
    id: 3,
    namaDepartemen: "Departemen Ginekologi",
    penanggungJawab: "Dr. Sarah Kurniawan",
    jamOperasional: "08:00 - 18:00",
    ruangan: "Gedung C, Lantai 1",
    lineTelp: "021-9876543",
    tanggalPembuatan: "2025-01-03",
    deskripsi: "Departemen yang menangani kesehatan wanita dan kehamilan.",
  },
  {
    id: 4,
    namaDepartemen: "Departemen Bedah Umum",
    penanggungJawab: "Dr. Arief Pratama",
    jamOperasional: "08:00 - 19:00",
    ruangan: "Gedung D, Lantai 4",
    lineTelp: "021-8765432",
    tanggalPembuatan: "2025-01-04",
    deskripsi: "Departemen yang menangani berbagai jenis operasi bedah umum.",
  },
  {
    id: 5,
    namaDepartemen: "Departemen Neurologi",
    penanggungJawab: "Dr. Bambang Saputra",
    jamOperasional: "09:00 - 17:00",
    ruangan: "Gedung E, Lantai 3",
    lineTelp: "021-6543210",
    tanggalPembuatan: "2025-01-05",
    deskripsi: "Departemen yang menangani kesehatan sistem saraf.",
  },
  {
    id: 6,
    namaDepartemen: "Departemen Onkologi",
    penanggungJawab: "Dr. Rina Adiwardana",
    jamOperasional: "08:00 - 16:30",
    ruangan: "Gedung F, Lantai 2",
    lineTelp: "021-4321098",
    tanggalPembuatan: "2025-01-06",
    deskripsi: "Departemen yang menangani diagnosis dan pengobatan kanker.",
  },
  {
    id: 7,
    namaDepartemen: "Departemen Ortopedi",
    penanggungJawab: "Dr. Fajar Nugroho",
    jamOperasional: "07:30 - 15:30",
    ruangan: "Gedung G, Lantai 1",
    lineTelp: "021-5432109",
    tanggalPembuatan: "2025-01-07",
    deskripsi: "Departemen yang menangani masalah kesehatan tulang dan sendi.",
  },
  {
    id: 8,
    namaDepartemen: "Departemen Psikiatri",
    penanggungJawab: "Dr. Dian Rahayu",
    jamOperasional: "08:00 - 17:00",
    ruangan: "Gedung H, Lantai 2",
    lineTelp: "021-3210987",
    tanggalPembuatan: "2025-01-08",
    deskripsi: "Departemen yang fokus pada kesehatan mental dan psikologi.",
  },
  {
    id: 9,
    namaDepartemen: "Departemen Dermatologi",
    penanggungJawab: "Dr. Yulianto Subekti",
    jamOperasional: "08:00 - 16:00",
    ruangan: "Gedung I, Lantai 3",
    lineTelp: "021-2109876",
    tanggalPembuatan: "2025-01-09",
    deskripsi: "Departemen yang menangani kesehatan kulit dan kelamin.",
  },
  {
    id: 10,
    namaDepartemen: "Departemen Urologi",
    penanggungJawab: "Dr. Ratna Widiastuti",
    jamOperasional: "09:00 - 17:30",
    ruangan: "Gedung J, Lantai 4",
    lineTelp: "021-1098765",
    tanggalPembuatan: "2025-01-10",
    deskripsi:
      "Departemen yang menangani kesehatan saluran kemih dan reproduksi pria.",
  },
  {
    id: 11,
    namaDepartemen: "Departemen Anestesiologi",
    penanggungJawab: "Dr. Sigit Hariyanto",
    jamOperasional: "07:00 - 15:00",
    ruangan: "Gedung K, Lantai 1",
    lineTelp: "021-9087654",
    tanggalPembuatan: "2025-01-11",
    deskripsi: "Departemen yang menangani anestesi dan manajemen nyeri.",
  },
  {
    id: 12,
    namaDepartemen: "Departemen Rehabilitasi Medis",
    penanggungJawab: "Dr. Lestari Wijaya",
    jamOperasional: "08:00 - 16:30",
    ruangan: "Gedung L, Lantai 2",
    lineTelp: "021-8098765",
    tanggalPembuatan: "2025-01-12",
    deskripsi:
      "Departemen yang menangani pemulihan pasca penyakit atau cedera.",
  },
  {
    id: 13,
    namaDepartemen: "Departemen Radiologi",
    penanggungJawab: "Dr. Indra Purnama",
    jamOperasional: "08:30 - 17:30",
    ruangan: "Gedung M, Lantai 3",
    lineTelp: "021-7098765",
    tanggalPembuatan: "2025-01-13",
    deskripsi:
      "Departemen yang menggunakan teknologi pencitraan untuk diagnosis.",
  },
];

export const administrasiRawatJalan = [
  {
    id: 1,
    namaAdministrasi: "Administrasi Pendaftaran",
    tipeRawat: "Rawat Jalan",
    tipeAdministrasi: "Pendaftaran",
    kelompokUsia: "Dewasa",
    departement: "Poli Anak",
    dataTarif: [
      { id: 1, groupPerusahaan: "standard", tarif: 20000, skb: 5000 },
      { id: 2, groupPerusahaan: "asuransi", tarif: 75000, skb: 10000 },
      { id: 3, groupPerusahaan: "YKKBI", tarif: 65000, skb: 8000 },
    ],
  },
  {
    id: 2,
    namaAdministrasi: "Biaya Konsultasi",
    tipeRawat: "Rawat Inap",
    tipeAdministrasi: "Pembayaran",
    kelompokUsia: "Anak-anak",
    departement: "Farmasi",
    dataTarif: [
      { id: 4, groupPerusahaan: "standard", tarif: 30000, skb: 7000 },
      { id: 5, groupPerusahaan: "asuransi", tarif: 90000, skb: 15000 },
    ],
  },
  {
    id: 3,
    namaAdministrasi: "Biaya Rawat Inap",
    tipeRawat: "Rawat Inap",
    tipeAdministrasi: "Pendaftaran",
    kelompokUsia: "Lansia",
    departement: "Radiologi",
    dataTarif: [
      { id: 6, groupPerusahaan: "standard", tarif: 40000, skb: 10000 },
      { id: 7, groupPerusahaan: "YKKBI", tarif: 85000, skb: 20000 },
    ],
  },
];

export const tarifTindakan = [
  {
    id: 1,
    namaKelas: "Suite",
    dokter: 100000,
    rs: 100000,
    JP: 100000,
    bpjs: 0,
    other: 0,
    total: 300000,
    kso: 0,
  },
  {
    id: 2,
    namaKelas: "Luxury",
    dokter: 50000,
    rs: 50000,
    JP: 50000,
    bpjs: 50000,
    other: 0,
    total: 200000,
    kso: 0,
  },
  {
    id: 3,
    namaKelas: "VIP Deluxe",
    dokter: 30000,
    rs: 30000,
    JP: 30000,
    bpjs: 30000,
    other: 0,
    total: 120000,
    kso: 0,
  },
];

export const group_tarif = [
  {
    id: 1,
    setup_tarif_id: 1,
    group_perusahaan: "Standar",
    persentase: 6,
    nilai_minimum: 0,
    nilai_maksimum: 600000,
  },
  {
    id: 2,
    setup_tarif_id: 1,
    group_perusahaan: "Asuransi",
    persentase: 6,
    nilai_minimum: 0,
    nilai_maksimum: 600000,
  },
  {
    id: 3,
    setup_tarif_id: 1,
    group_perusahaan: "BPJS",
    persentase: 6,
    nilai_minimum: 0,
    nilai_maksimum: 250000,
  },
  {
    id: 4,
    setup_tarif_id: 1,
    group_perusahaan: "RS MMC",
    persentase: 6,
    nilai_minimum: 0,
    nilai_maksimum: 350000,
  },
  {
    id: 5,
    setup_tarif_id: 2,
    group_perusahaan: "Standar",
    persentase: 8,
    nilai_minimum: 100000,
    nilai_maksimum: 700000,
  },
  {
    id: 6,
    setup_tarif_id: 2,
    group_perusahaan: "Asuransi",
    persentase: 8,
    nilai_minimum: 150000,
    nilai_maksimum: 700000,
  },
  {
    id: 7,
    setup_tarif_id: 2,
    group_perusahaan: "BPJS",
    persentase: 8,
    nilai_minimum: 0,
    nilai_maksimum: 300000,
  },
  {
    id: 8,
    setup_tarif_id: 2,
    group_perusahaan: "RS MMC",
    persentase: 8,
    nilai_minimum: 0,
    nilai_maksimum: 400000,
  },
  {
    id: 9,
    setup_tarif_id: 3,
    group_perusahaan: "Standar",
    persentase: 10,
    nilai_minimum: 200000,
    nilai_maksimum: 800000,
  },
  {
    id: 10,
    setup_tarif_id: 3,
    group_perusahaan: "Asuransi",
    persentase: 10,
    nilai_minimum: 250000,
    nilai_maksimum: 800000,
  },
  {
    id: 11,
    setup_tarif_id: 3,
    group_perusahaan: "BPJS",
    persentase: 10,
    nilai_minimum: 100000,
    nilai_maksimum: 350000,
  },
  {
    id: 12,
    setup_tarif_id: 3,
    group_perusahaan: "RS MMC",
    persentase: 10,
    nilai_minimum: 100000,
    nilai_maksimum: 450000,
  },
  {
    id: 13,
    setup_tarif_id: 4,
    group_perusahaan: "Standar",
    persentase: 12,
    nilai_minimum: 300000,
    nilai_maksimum: 900000,
  },
  {
    id: 14,
    setup_tarif_id: 4,
    group_perusahaan: "Asuransi",
    persentase: 12,
    nilai_minimum: 350000,
    nilai_maksimum: 900000,
  },
  {
    id: 15,
    setup_tarif_id: 4,
    group_perusahaan: "BPJS",
    persentase: 12,
    nilai_minimum: 200000,
    nilai_maksimum: 400000,
  },
];

export const tarifPoliKlinik = [
  {
    id: 1,
    kode: "AN5001",
    namaTindakan: "Anastesi Epdural",
    namaPoliKlinik: "Anasteologi",
    dokter: 130000,
    rumahSakit: 20000,
    jp: 0,
    bahp: 0,
    lainLain: 0,
    total: "Rp. " + (150000).toLocaleString("id-ID"),
    kso: 0,
  },
  {
    id: 2,
    kode: "OB3002",
    namaTindakan: "USG Kehamilan",
    namaPoliKlinik: "Obstetri",
    dokter: 80000,
    rumahSakit: 15000,
    jp: 0,
    bahp: 0,
    lainLain: 0,
    total: "Rp. " + (95000).toLocaleString("id-ID"),
    kso: 0,
  },
  {
    id: 3,
    kode: "PD4003",
    namaTindakan: "Konsultasi Penyakit Dalam",
    namaPoliKlinik: "Penyakit Dalam",
    dokter: 120000,
    rumahSakit: 25000,
    jp: 0,
    bahp: 0,
    lainLain: 0,
    total: "Rp. " + (145000).toLocaleString("id-ID"),
    kso: 0,
  },
  {
    id: 4,
    kode: "GD6004",
    namaTindakan: "Pertolongan Pertama Luka Berat",
    namaPoliKlinik: "Gawat Darurat",
    dokter: 100000,
    rumahSakit: 30000,
    jp: 0,
    bahp: 0,
    lainLain: 0,
    total: "Rp. " + (130000).toLocaleString("id-ID"),
    kso: 0,
  },
  {
    id: 5,
    kode: "OR7005",
    namaTindakan: "Operasi Apendisitis",
    namaPoliKlinik: "Bedah",
    dokter: 500000,
    rumahSakit: 100000,
    jp: 50000,
    bahp: 0,
    lainLain: 0,
    total: "Rp. " + (650000).toLocaleString("id-ID"),
    kso: 0,
  },
  {
    id: 6,
    kode: "KU8006",
    namaTindakan: "Konsultasi Psikologi",
    namaPoliKlinik: "Kesehatan Jiwa",
    dokter: 110000,
    rumahSakit: 15000,
    jp: 0,
    bahp: 0,
    lainLain: 0,
    total: "Rp. " + (125000).toLocaleString("id-ID"),
    kso: 0,
  },
  {
    id: 7,
    kode: "SP9007",
    namaTindakan: "Pemeriksaan Retina",
    namaPoliKlinik: "Spesialis Mata",
    dokter: 150000,
    rumahSakit: 20000,
    jp: 0,
    bahp: 0,
    lainLain: 0,
    total: "Rp. " + (170000).toLocaleString("id-ID"),
    kso: 0,
  },
  {
    id: 8,
    kode: "OR7012",
    namaTindakan: "Operasi Katarak",
    namaPoliKlinik: "Bedah Mata",
    dokter: 400000,
    rumahSakit: 75000,
    jp: 50000,
    bahp: 0,
    lainLain: 0,
    total: "Rp. " + (525000).toLocaleString("id-ID"),
    kso: 0,
  },
  {
    id: 9,
    kode: "KM2009",
    namaTindakan: "Pembersihan Gigi dan Karang",
    namaPoliKlinik: "Gigi dan Mulut",
    dokter: 100000,
    rumahSakit: 10000,
    jp: 0,
    bahp: 0,
    lainLain: 0,
    total: "Rp. " + (110000).toLocaleString("id-ID"),
    kso: 0,
  },
  {
    id: 10,
    kode: "KB1010",
    namaTindakan: "Pasang IUD",
    namaPoliKlinik: "Kebidanan",
    dokter: 200000,
    rumahSakit: 50000,
    jp: 0,
    bahp: 0,
    lainLain: 0,
    total: "Rp. " + (250000).toLocaleString("id-ID"),
    kso: 0,
  },
  {
    id: 11,
    kode: "SP2011",
    namaTindakan: "Pemeriksaan Neurologis",
    namaPoliKlinik: "Saraf",
    dokter: 170000,
    rumahSakit: 25000,
    jp: 0,
    bahp: 0,
    lainLain: 0,
    total: "Rp. " + (195000).toLocaleString("id-ID"),
    kso: 0,
  },
  {
    id: 12,
    kode: "RM3012",
    namaTindakan: "MRI Scan",
    namaPoliKlinik: "Radiologi",
    dokter: 500000,
    rumahSakit: 100000,
    jp: 50000,
    bahp: 0,
    lainLain: 0,
    total: "Rp. " + (650000).toLocaleString("id-ID"),
    kso: 0,
  },
  {
    id: 13,
    kode: "FR4013",
    namaTindakan: "Fisioterapi Lutut",
    namaPoliKlinik: "Fisioterapi",
    dokter: 80000,
    rumahSakit: 20000,
    jp: 0,
    bahp: 0,
    lainLain: 0,
    total: "Rp. " + (100000).toLocaleString("id-ID"),
    kso: 0,
  },
  {
    id: 14,
    kode: "AN5014",
    namaTindakan: "Anastesi Umum",
    namaPoliKlinik: "Anasteologi",
    dokter: 300000,
    rumahSakit: 50000,
    jp: 0,
    bahp: 0,
    lainLain: 0,
    total: "Rp. " + (350000).toLocaleString("id-ID"),
    kso: 0,
  },
  {
    id: 15,
    kode: "KU6015",
    namaTindakan: "Konseling Keluarga",
    namaPoliKlinik: "Psikologi",
    dokter: 100000,
    rumahSakit: 20000,
    jp: 0,
    bahp: 0,
    lainLain: 0,
    total: "Rp. " + (120000).toLocaleString("id-ID"),
    kso: 0,
  },
];
