export const jadwalDokterByDate = {
  "2025-01-13": [
    {
      id: 16,
      label: "Dr. Aaron Pierce",
      department: "Endocrinology",
      waktuPraktek: "09:00 - 17:00",
      noUrut: 1,
    },
    {
      id: 17,
      label: "Dr. Betty Cooper",
      department: "Gastroenterology",
      waktuPraktek: "08:00 - 16:00",
      noUrut: 2,
    },
    {
      id: 18,
      label: "Dr. Charles Xavier",
      department: "Radiology",
      waktuPraktek: "14:00 - 22:00",
      noUrut: 3,
    },
    {
      id: 19,
      label: "Dr. Diana Prince",
      department: "Emergency Medicine",
      waktuPraktek: "07:00 - 15:00",
      noUrut: 4,
    },
    {
      id: 20,
      label: "Dr. Edward Nygma",
      department: "Rheumatology",
      waktuPraktek: "13:00 - 21:00",
      noUrut: 5,
    },
    {
      id: 21,
      label: "Dr. Fiona Gallagher",
      department: "Immunology",
      waktuPraktek: "08:00 - 14:00",
      noUrut: 6,
    },
    {
      id: 22,
      label: "Dr. Gordon Freeman",
      department: "Hematology",
      waktuPraktek: "10:00 - 19:00",
      noUrut: 7,
    },
    {
      id: 23,
      label: "Dr. Harvey Dent",
      department: "Dental",
      waktuPraktek: "09:00 - 17:00",
      noUrut: 8,
    },
    {
      id: 24,
      label: "Dr. Ivy Pepper",
      department: "Allergy and Immunology",
      waktuPraktek: "11:00 - 18:00",
      noUrut: 9,
    },
    {
      id: 25,
      label: "Dr. Jake Peralta",
      department: "Neurology",
      waktuPraktek: "07:00 - 13:00",
      noUrut: 10,
    },
  ],
  "2025-01-14": [
    {
      id: 26,
      label: "Dr. Kara Danvers",
      department: "OB/GYN",
      waktuPraktek: "10:00 - 19:00",
      noUrut: 1,
    },
    {
      id: 27,
      label: "Dr. Leonard McCoy",
      department: "Geriatrics",
      waktuPraktek: "09:00 - 17:00",
      noUrut: 2,
    },
    {
      id: 28,
      label: "Dr. Monica Hall",
      department: "General Surgery",
      waktuPraktek: "08:00 - 16:00",
      noUrut: 3,
    },
    {
      id: 29,
      label: "Dr. Nigel Murray",
      department: "Pathology",
      waktuPraktek: "14:00 - 22:00",
      noUrut: 4,
    },
    {
      id: 30,
      label: "Dr. Oswald Cobblepot",
      department: "Pediatrics",
      waktuPraktek: "07:00 - 15:00",
      noUrut: 5,
    },
    {
      id: 31,
      label: "Dr. Peggy Carter",
      department: "Cardiology",
      waktuPraktek: "13:00 - 21:00",
      noUrut: 6,
    },
    {
      id: 32,
      label: "Dr. Quentin Lance",
      department: "Pulmonology",
      waktuPraktek: "08:00 - 14:00",
      noUrut: 7,
    },
    {
      id: 33,
      label: "Dr. Rachel Green",
      department: "Dermatology",
      waktuPraktek: "10:00 - 18:00",
      noUrut: 8,
    },
    {
      id: 34,
      label: "Dr. Sheldon Cooper",
      department: "Physics",
      waktuPraktek: "12:00 - 19:00",
      noUrut: 9,
    },
    {
      id: 35,
      label: "Dr. Tony Stark",
      department: "Biomedical Engineering",
      waktuPraktek: "09:00 - 17:00",
      noUrut: 10,
    },
  ],
  "2025-01-15": [
    {
      id: 36,
      label: "Dr. Ulrich Stern",
      department: "Neurosurgery",
      waktuPraktek: "10:00 - 18:00",
      noUrut: 1,
    },
    {
      id: 37,
      label: "Dr. Victor Fries",
      department: "Cryogenics",
      waktuPraktek: "08:00 - 16:00",
      noUrut: 2,
    },
    {
      id: 38,
      label: "Dr. Walter Bishop",
      department: "Psychiatry",
      waktuPraktek: "14:00 - 22:00",
      noUrut: 3,
    },
    {
      id: 39,
      label: "Dr. Xavier Mendel",
      department: "Genetics",
      waktuPraktek: "07:00 - 15:00",
      noUrut: 4,
    },
    {
      id: 40,
      label: "Dr. Yvonne Hartman",
      department: "OB/GYN",
      waktuPraktek: "13:00 - 21:00",
      noUrut: 5,
    },
    {
      id: 41,
      label: "Dr. Zelda Spellman",
      department: "Occult Sciences",
      waktuPraktek: "08:00 - 14:00",
      noUrut: 6,
    },
    {
      id: 42,
      label: "Dr. Abigail Sciuto",
      department: "Forensic Science",
      waktuPraktek: "10:00 - 19:00",
      noUrut: 7,
    },
    {
      id: 43,
      label: "Dr. Barney Stinson",
      department: "Therapeutic Comedy",
      waktuPraktek: "09:00 - 17:00",
      noUrut: 8,
    },
    {
      id: 44,
      label: "Dr. Claire Temple",
      department: "Emergency Medicine",
      waktuPraktek: "11:00 - 18:00",
      noUrut: 9,
    },
    {
      id: 45,
      label: "Dr. Derek Morgan",
      department: "Behavioral Analysis",
      waktuPraktek: "07:00 - 13:00",
      noUrut: 10,
    },
  ],
  "2025-01-16": [
    {
      id: 46,
      label: "Dr. Emma Swan",
      department: "General Medicine",
      waktuPraktek: "10:00 - 19:00",
      noUrut: 1,
    },
    {
      id: 47,
      label: "Dr. Frank Castle",
      department: "Trauma Surgery",
      waktuPraktek: "09:00 - 17:00",
      noUrut: 2,
    },
    {
      id: 48,
      label: "Dr. George Weasley",
      department: "Magical Maladies",
      waktuPraktek: "08:00 - 16:00",
      noUrut: 3,
    },
    {
      id: 49,
      label: "Dr. Harry Wells",
      department: "Theoretical Physics",
      waktuPraktek: "14:00 - 22:00",
      noUrut: 4,
    },
    {
      id: 50,
      label: "Dr. Iris West-Allen",
      department: "Journalism",
      waktuPraktek: "07:00 - 15:00",
      noUrut: 5,
    },
    {
      id: 51,
      label: "Dr. Joan Watson",
      department: "Psychiatry",
      waktuPraktek: "13:00 - 21:00",
      noUrut: 6,
    },
    {
      id: 52,
      label: "Dr. Katniss Everdeen",
      department: "Archery Medicine",
      waktuPraktek: "08:00 - 14:00",
      noUrut: 7,
    },
    {
      id: 53,
      label: "Dr. Lex Luthor",
      department: "Business Strategy",
      waktuPraktek: "10:00 - 18:00",
      noUrut: 8,
    },
    {
      id: 54,
      label: "Dr. Molly Hooper",
      department: "Pathology",
      waktuPraktek: "12:00 - 19:00",
      noUrut: 9,
    },
    {
      id: 55,
      label: "Dr. Nora Allen",
      department: "Temporal Medicine",
      waktuPraktek: "09:00 - 17:00",
      noUrut: 10,
    },
  ],
  "2025-01-17": [
    {
      id: 56,
      label: "Dr. Oliver Queen",
      department: "Archery Therapy",
      waktuPraktek: "10:00 - 18:00",
      noUrut: 1,
    },
    {
      id: 57,
      label: "Dr. Peter Parker",
      department: "Arachnology",
      waktuPraktek: "08:00 - 16:00",
      noUrut: 2,
    },
    {
      id: 58,
      label: "Dr. Quentin Coldwater",
      department: "Magical Health",
      waktuPraktek: "14:00 - 22:00",
      noUrut: 3,
    },
    {
      id: 59,
      label: "Dr. Remy Hadley",
      department: "Internal Medicine",
      waktuPraktek: "07:00 - 15:00",
      noUrut: 4,
    },
    {
      id: 60,
      label: "Dr. Sarah Lance",
      department: "Time Travel Medicine",
      waktuPraktek: "13:00 - 21:00",
      noUrut: 5,
    },
    {
      id: 61,
      label: "Dr. Thea Queen",
      department: "Archery Therapy",
      waktuPraktek: "08:00 - 14:00",
      noUrut: 6,
    },
    {
      id: 62,
      label: "Dr. Ultron",
      department: "Robotics",
      waktuPraktek: "10:00 - 19:00",
      noUrut: 7,
    },
    {
      id: 63,
      label: "Dr. Vandal Savage",
      department: "Historical Medicine",
      waktuPraktek: "09:00 - 17:00",
      noUrut: 8,
    },
    {
      id: 64,
      label: "Dr. Wally West",
      department: "Speed Force Physiology",
      waktuPraktek: "11:00 - 18:00",
      noUrut: 9,
    },
    {
      id: 65,
      label: "Dr. Xander Harris",
      department: "Occult Emergency",
      waktuPraktek: "07:00 - 13:00",
      noUrut: 10,
    },
  ],
};

// File: data.js
export const dataKelasTersedia = [
  {
    Kelas: "Suite",
    Keterangan: "-",
    JmlRuang: 8,
    JmlTempatTidur: 23,
    JmlTerisi: 2,
    JmlReservasi: 0,
  },
  {
    Kelas: "Luxury",
    Keterangan: "-",
    JmlRuang: 6,
    JmlTempatTidur: 12,
    JmlTerisi: 2,
    JmlReservasi: 1,
  },
  {
    Kelas: "Isolasi Lavender SVP",
    Keterangan: "Isolasi Lavender SVP",
    JmlRuang: 0,
    JmlTempatTidur: 0,
    JmlTerisi: 0,
    JmlReservasi: 0,
  },
  {
    Kelas: "Deluxe",
    Keterangan: "-",
    JmlRuang: 4,
    JmlTempatTidur: 10,
    JmlTerisi: 3,
    JmlReservasi: 2,
  },
  {
    Kelas: "Standard",
    Keterangan: "-",
    JmlRuang: 10,
    JmlTempatTidur: 20,
    JmlTerisi: 10,
    JmlReservasi: 5,
  },
  {
    Kelas: "Economy",
    Keterangan: "-",
    JmlRuang: 12,
    JmlTempatTidur: 24,
    JmlTerisi: 12,
    JmlReservasi: 6,
  },
  {
    Kelas: "Royal",
    Keterangan: "-",
    JmlRuang: 2,
    JmlTempatTidur: 4,
    JmlTerisi: 1,
    JmlReservasi: 0,
  },
  {
    Kelas: "Presidential",
    Keterangan: "VIP",
    JmlRuang: 3,
    JmlTempatTidur: 6,
    JmlTerisi: 3,
    JmlReservasi: 1,
  },
  {
    Kelas: "Shared",
    Keterangan: "Multiple beds",
    JmlRuang: 15,
    JmlTempatTidur: 30,
    JmlTerisi: 15,
    JmlReservasi: 7,
  },
  {
    Kelas: "Single",
    Keterangan: "-",
    JmlRuang: 20,
    JmlTempatTidur: 20,
    JmlTerisi: 10,
    JmlReservasi: 5,
  },
  {
    Kelas: "Double",
    Keterangan: "-",
    JmlRuang: 5,
    JmlTempatTidur: 10,
    JmlTerisi: 5,
    JmlReservasi: 3,
  },
  {
    Kelas: "Triple",
    Keterangan: "-",
    JmlRuang: 3,
    JmlTempatTidur: 9,
    JmlTerisi: 3,
    JmlReservasi: 1,
  },
  {
    Kelas: "VIP",
    Keterangan: "Extra service",
    JmlRuang: 2,
    JmlTempatTidur: 4,
    JmlTerisi: 2,
    JmlReservasi: 2,
  },
  {
    Kelas: "Master Suite",
    Keterangan: "Luxury",
    JmlRuang: 1,
    JmlTempatTidur: 2,
    JmlTerisi: 1,
    JmlReservasi: 0,
  },
  {
    Kelas: "Studio",
    Keterangan: "Open space",
    JmlRuang: 5,
    JmlTempatTidur: 10,
    JmlTerisi: 4,
    JmlReservasi: 2,
  },
];

export const dataOperasiTersedia = {
  "2025-01-10": [
    {
      jamMulai: "08:00",
      jamSelesai: "09:30",
      estimasi: 90,
      dokterOperator: "Dr. Ahmad",
      tindakan: "Appendectomy",
      ruangan: "OK I",
    },
    {
      jamMulai: "10:00",
      jamSelesai: "11:00",
      estimasi: 60,
      dokterOperator: "Dr. Budi",
      tindakan: "Cholecystectomy",
      ruangan: "OK II",
    },
    {
      jamMulai: "11:15",
      jamSelesai: "12:15",
      estimasi: 60,
      dokterOperator: "Dr. Cici",
      tindakan: "Hernia Repair",
      ruangan: "OK III",
    },
    {
      jamMulai: "13:00",
      jamSelesai: "14:30",
      estimasi: 90,
      dokterOperator: "Dr. Dedi",
      tindakan: "Hip Replacement",
      ruangan: "OK IV",
    },
    {
      jamMulai: "14:45",
      jamSelesai: "15:45",
      estimasi: 60,
      dokterOperator: "Dr. Eka",
      tindakan: "Knee Surgery",
      ruangan: "OK V",
    },
    {
      jamMulai: "16:00",
      jamSelesai: "17:30",
      estimasi: 90,
      dokterOperator: "Dr. Fira",
      tindakan: "Mastectomy",
      ruangan: "OK VI",
    },
    {
      jamMulai: "17:45",
      jamSelesai: "18:45",
      estimasi: 60,
      dokterOperator: "Dr. Gilang",
      tindakan: "Pacemaker Insertion",
      ruangan: "OK VII",
    },
    {
      jamMulai: "19:00",
      jamSelesai: "20:00",
      estimasi: 60,
      dokterOperator: "Dr. Hilda",
      tindakan: "Gastric Bypass",
      ruangan: "OK VIII",
    },
    {
      jamMulai: "20:15",
      jamSelesai: "21:45",
      estimasi: 90,
      dokterOperator: "Dr. Iskandar",
      tindakan: "Thyroidectomy",
      ruangan: "OK IX",
    },
    {
      jamMulai: "22:00",
      jamSelesai: "23:00",
      estimasi: 60,
      dokterOperator: "Dr. Jihan",
      tindakan: "Cesarean Section",
      ruangan: "OK X",
    },
  ],
  "2025-01-11": [
    {
      jamMulai: "08:00",
      jamSelesai: "09:30",
      estimasi: 90,
      dokterOperator: "Dr. Fani",
      tindakan: "Laminectomy",
      ruangan: "OK VI",
    },
    {
      jamMulai: "10:00",
      jamSelesai: "11:00",
      estimasi: 60,
      dokterOperator: "Dr. Gita",
      tindakan: "Cataract Surgery",
      ruangan: "OK VII",
    },
    {
      jamMulai: "11:15",
      jamSelesai: "12:15",
      estimasi: 60,
      dokterOperator: "Dr. Hani",
      tindakan: "Tonsillectomy",
      ruangan: "OK VIII",
    },
    {
      jamMulai: "13:00",
      jamSelesai: "14:30",
      estimasi: 90,
      dokterOperator: "Dr. Indah",
      tindakan: "Coronary Artery Bypass",
      ruangan: "OK IX",
    },
    {
      jamMulai: "14:45",
      jamSelesai: "15:45",
      estimasi: 60,
      dokterOperator: "Dr. Joko",
      tindakan: "Heart Valve Repair",
      ruangan: "OK X",
    },
    {
      jamMulai: "16:00",
      jamSelesai: "17:30",
      estimasi: 90,
      dokterOperator: "Dr. Karina",
      tindakan: "Lung Transplant",
      ruangan: "Endoscopy I",
    },
    {
      jamMulai: "17:45",
      jamSelesai: "18:45",
      estimasi: 60,
      dokterOperator: "Dr. Luthfi",
      tindakan: "Prostate Biopsy",
      ruangan: "Endoscopy II",
    },
    {
      jamMulai: "19:00",
      jamSelesai: "20:00",
      estimasi: 60,
      dokterOperator: "Dr. Mirna",
      tindakan: "Rhinoplasty",
      ruangan: "Endoscopy III",
    },
    {
      jamMulai: "20:15",
      jamSelesai: "21:45",
      estimasi: 90,
      dokterOperator: "Dr. Nabila",
      tindakan: "Facelift",
      ruangan: "Endoscopy IV",
    },
    {
      jamMulai: "22:00",
      jamSelesai: "23:00",
      estimasi: 60,
      dokterOperator: "Dr. Opan",
      tindakan: "Bladder Surgery",
      ruangan: "Endoscopy V",
    },
  ],
  "2025-01-12": [
    {
      jamMulai: "08:00",
      jamSelesai: "09:30",
      estimasi: 90,
      dokterOperator: "Dr. Kiki",
      tindakan: "Angioplasty",
      ruangan: "Endoscopy I",
    },
    {
      jamMulai: "10:00",
      jamSelesai: "11:00",
      estimasi: 60,
      dokterOperator: "Dr. Lina",
      tindakan: "Adenoidectomy",
      ruangan: "Endoscopy II",
    },
    {
      jamMulai: "11:15",
      jamSelesai: "12:15",
      estimasi: 60,
      dokterOperator: "Dr. Maman",
      tindakan: "Spinal Fusion",
      ruangan: "Endoscopy III",
    },
    {
      jamMulai: "13:00",
      jamSelesai: "14:30",
      estimasi: 90,
      dokterOperator: "Dr. Nana",
      tindakan: "Breast Biopsy",
      ruangan: "Endoscopy IV",
    },
    {
      jamMulai: "14:45",
      jamSelesai: "15:45",
      estimasi: 60,
      dokterOperator: "Dr. Oka",
      tindakan: "Prostatectomy",
      ruangan: "Endoscopy V",
    },
    {
      jamMulai: "16:00",
      jamSelesai: "17:30",
      estimasi: 90,
      dokterOperator: "Dr. Pia",
      tindakan: "Vasectomy",
      ruangan: "OK I",
    },
    {
      jamMulai: "17:45",
      jamSelesai: "18:45",
      estimasi: 60,
      dokterOperator: "Dr. Qori",
      tindakan: "Skin Graft",
      ruangan: "OK II",
    },
    {
      jamMulai: "19:00",
      jamSelesai: "20:00",
      estimasi: 60,
      dokterOperator: "Dr. Rani",
      tindakan: "Varicose Vein Surgery",
      ruangan: "OK III",
    },
    {
      jamMulai: "20:15",
      jamSelesai: "21:45",
      estimasi: 90,
      dokterOperator: "Dr. Santi",
      tindakan: "Kidney Transplant",
      ruangan: "OK IV",
    },
    {
      jamMulai: "22:00",
      jamSelesai: "23:00",
      estimasi: 60,
      dokterOperator: "Dr. Tono",
      tindakan: "Liver Transplant",
      ruangan: "OK V",
    },
  ],
};

export const dataBookingBed = [
  {
    no: "1",
    kelas: "VIP DELUXE",
    ruangan: "VIP DELUXE",
    beds: [
      { bed: "802 - center", status: "Free" },
      { bed: "805 - center", status: "Booked" },
      { bed: "807 - center", status: "Occupied" },
    ],
  },
  {
    no: "2",
    kelas: "VIP",
    ruangan: "VIP",
    beds: [
      { bed: "304 - left", status: "Free" },
      { bed: "308 - left", status: "Occupied" },
      { bed: "407 - left", status: "Free" },
    ],
  },
  {
    no: "3",
    kelas: "Regular",
    ruangan: "Regular 1",
    beds: [
      { bed: "210 - right", status: "Booked" },
      { bed: "211 - right", status: "Occupied" },
      { bed: "212 - right", status: "Free" },
    ],
  },
  {
    no: "4",
    kelas: "Economy",
    ruangan: "Economy 1",
    beds: [
      { bed: "115 - left", status: "Free" },
      { bed: "117 - left", status: "Occupied" },
    ],
  },
  {
    no: "5",
    kelas: "Economy",
    ruangan: "Economy 2",
    beds: [
      { bed: "120 - right", status: "Booked" },
      { bed: "121 - right", status: "Free" },
    ],
  },
  {
    no: "6",
    kelas: "Regular",
    ruangan: "Regular 2",
    beds: [
      { bed: "305 - center", status: "Occupied" },
      { bed: "306 - center", status: "Free" },
      { bed: "307 - center", status: "Free" },
    ],
  },
  {
    no: "7",
    kelas: "VIP",
    ruangan: "VIP 2",
    beds: [
      { bed: "401 - left", status: "Free" },
      { bed: "402 - left", status: "Booked" },
    ],
  },
  {
    no: "8",
    kelas: "VIP DELUXE",
    ruangan: "VIP DELUXE 2",
    beds: [
      { bed: "501 - center", status: "Occupied" },
      { bed: "502 - center", status: "Free" },
    ],
  },
  {
    no: "9",
    kelas: "Regular",
    ruangan: "Regular 3",
    beds: [
      { bed: "310 - right", status: "Booked" },
      { bed: "311 - right", status: "Occupied" },
    ],
  },
  {
    no: "10",
    kelas: "Economy",
    ruangan: "Economy 3",
    beds: [
      { bed: "123 - left", status: "Free" },
      { bed: "125 - left", status: "Occupied" },
    ],
  },
];
