export const jadwalDokterByDate = {
  "2025-01-09": [
    {
      id: 1,
      label: "Dr. John Doe",
      department: "Cardiology",
      waktuPraktek: "10:00 - 19:00",
      noUrut: 1,
    },
    {
      id: 2,
      label: "Dr. Jane Smith",
      department: "Neurology",
      waktuPraktek: "09:00 - 17:00",
      noUrut: 2,
    },
    {
      id: 5,
      label: "Dr. Eric Taylor",
      department: "Orthopedics",
      waktuPraktek: "08:00 - 16:00",
      noUrut: 3,
    },
    {
      id: 6,
      label: "Dr. Nancy Drew",
      department: "Dermatology",
      waktuPraktek: "13:00 - 20:00",
      noUrut: 4,
    },
    {
      id: 7,
      label: "Dr. Lisa Cuddy",
      department: "General Medicine",
      waktuPraktek: "11:00 - 18:00",
      noUrut: 5,
    },
  ],
  "2025-01-10": [
    {
      id: 3,
      label: "Dr. Alice Brown",
      department: "Pediatrics",
      waktuPraktek: "08:00 - 14:00",
      noUrut: 1,
    },
    {
      id: 4,
      label: "Dr. Xavier Adams",
      department: "General Surgery",
      waktuPraktek: "14:00 - 20:00",
      noUrut: 2,
    },
    {
      id: 8,
      label: "Dr. Omar Little",
      department: "Psychiatry",
      waktuPraktek: "12:00 - 19:00",
      noUrut: 3,
    },
    {
      id: 9,
      label: "Dr. Gregory House",
      department: "Nephrology",
      waktuPraktek: "07:00 - 15:00",
      noUrut: 4,
    },
    {
      id: 10,
      label: "Dr. Meredith Grey",
      department: "Surgery",
      waktuPraktek: "10:00 - 18:00",
      noUrut: 5,
    },
  ],
  "2025-01-11": [
    {
      id: 11,
      label: "Dr. Derek Shepherd",
      department: "Neurosurgery",
      waktuPraktek: "09:00 - 17:00",
      noUrut: 1,
    },
    {
      id: 12,
      label: "Dr. Christina Yang",
      department: "Cardiothoracic Surgery",
      waktuPraktek: "08:00 - 16:00",
      noUrut: 2,
    },
    {
      id: 13,
      label: "Dr. George O'Malley",
      department: "Trauma Surgery",
      waktuPraktek: "14:00 - 22:00",
      noUrut: 3,
    },
    {
      id: 14,
      label: "Dr. Izzie Stevens",
      department: "Oncology",
      waktuPraktek: "07:00 - 15:00",
      noUrut: 4,
    },
    {
      id: 15,
      label: "Dr. Alex Karev",
      department: "Pediatric Surgery",
      waktuPraktek: "13:00 - 21:00",
      noUrut: 5,
    },
  ],
};

// File: data.js
export const dataKelasTersedia = [
  {
    Kelas: "Suite",
    Keterangan: "-",
    JmlRuang: 8,
    JmlTempatTidur: 23,
    JmlTerisi: 2,
    JmlReservasi: 0,
  },
  {
    Kelas: "Luxury",
    Keterangan: "-",
    JmlRuang: 6,
    JmlTempatTidur: 12,
    JmlTerisi: 2,
    JmlReservasi: 1,
  },
  {
    Kelas: "Isolasi Lavender SVP",
    Keterangan: "Isolasi Lavender SVP",
    JmlRuang: 0,
    JmlTempatTidur: 0,
    JmlTerisi: 0,
    JmlReservasi: 0,
  },
  {
    Kelas: "Deluxe",
    Keterangan: "-",
    JmlRuang: 4,
    JmlTempatTidur: 10,
    JmlTerisi: 3,
    JmlReservasi: 2,
  },
  {
    Kelas: "Standard",
    Keterangan: "-",
    JmlRuang: 10,
    JmlTempatTidur: 20,
    JmlTerisi: 10,
    JmlReservasi: 5,
  },
  {
    Kelas: "Economy",
    Keterangan: "-",
    JmlRuang: 12,
    JmlTempatTidur: 24,
    JmlTerisi: 12,
    JmlReservasi: 6,
  },
  {
    Kelas: "Royal",
    Keterangan: "-",
    JmlRuang: 2,
    JmlTempatTidur: 4,
    JmlTerisi: 1,
    JmlReservasi: 0,
  },
  {
    Kelas: "Presidential",
    Keterangan: "VIP",
    JmlRuang: 3,
    JmlTempatTidur: 6,
    JmlTerisi: 3,
    JmlReservasi: 1,
  },
  {
    Kelas: "Shared",
    Keterangan: "Multiple beds",
    JmlRuang: 15,
    JmlTempatTidur: 30,
    JmlTerisi: 15,
    JmlReservasi: 7,
  },
  {
    Kelas: "Single",
    Keterangan: "-",
    JmlRuang: 20,
    JmlTempatTidur: 20,
    JmlTerisi: 10,
    JmlReservasi: 5,
  },
  {
    Kelas: "Double",
    Keterangan: "-",
    JmlRuang: 5,
    JmlTempatTidur: 10,
    JmlTerisi: 5,
    JmlReservasi: 3,
  },
  {
    Kelas: "Triple",
    Keterangan: "-",
    JmlRuang: 3,
    JmlTempatTidur: 9,
    JmlTerisi: 3,
    JmlReservasi: 1,
  },
  {
    Kelas: "VIP",
    Keterangan: "Extra service",
    JmlRuang: 2,
    JmlTempatTidur: 4,
    JmlTerisi: 2,
    JmlReservasi: 2,
  },
  {
    Kelas: "Master Suite",
    Keterangan: "Luxury",
    JmlRuang: 1,
    JmlTempatTidur: 2,
    JmlTerisi: 1,
    JmlReservasi: 0,
  },
  {
    Kelas: "Studio",
    Keterangan: "Open space",
    JmlRuang: 5,
    JmlTempatTidur: 10,
    JmlTerisi: 4,
    JmlReservasi: 2,
  },
];

export const dataOperasiTersedia = {
  "2025-01-10": [
    {
      jamMulai: "08:00",
      jamSelesai: "09:30",
      estimasi: 90,
      dokterOperator: "Dr. Ahmad",
      tindakan: "Appendectomy",
      ruangan: "OK I",
    },
    {
      jamMulai: "10:00",
      jamSelesai: "11:00",
      estimasi: 60,
      dokterOperator: "Dr. Budi",
      tindakan: "Cholecystectomy",
      ruangan: "OK II",
    },
    {
      jamMulai: "11:15",
      jamSelesai: "12:15",
      estimasi: 60,
      dokterOperator: "Dr. Cici",
      tindakan: "Hernia Repair",
      ruangan: "OK III",
    },
    {
      jamMulai: "13:00",
      jamSelesai: "14:30",
      estimasi: 90,
      dokterOperator: "Dr. Dedi",
      tindakan: "Hip Replacement",
      ruangan: "OK IV",
    },
    {
      jamMulai: "14:45",
      jamSelesai: "15:45",
      estimasi: 60,
      dokterOperator: "Dr. Eka",
      tindakan: "Knee Surgery",
      ruangan: "OK V",
    },
  ],
  "2025-01-11": [
    {
      jamMulai: "08:00",
      jamSelesai: "09:30",
      estimasi: 90,
      dokterOperator: "Dr. Fani",
      tindakan: "Laminectomy",
      ruangan: "OK VI",
    },
    {
      jamMulai: "10:00",
      jamSelesai: "11:00",
      estimasi: 60,
      dokterOperator: "Dr. Gita",
      tindakan: "Cataract Surgery",
      ruangan: "OK VII",
    },
    {
      jamMulai: "11:15",
      jamSelesai: "12:15",
      estimasi: 60,
      dokterOperator: "Dr. Hani",
      tindakan: "Tonsillectomy",
      ruangan: "OK VIII",
    },
    {
      jamMulai: "13:00",
      jamSelesai: "14:30",
      estimasi: 90,
      dokterOperator: "Dr. Indah",
      tindakan: "Coronary Artery Bypass",
      ruangan: "OK IX",
    },
    {
      jamMulai: "14:45",
      jamSelesai: "15:45",
      estimasi: 60,
      dokterOperator: "Dr. Joko",
      tindakan: "Heart Valve Repair",
      ruangan: "OK X",
    },
  ],
  "2025-01-12": [
    {
      jamMulai: "08:00",
      jamSelesai: "09:30",
      estimasi: 90,
      dokterOperator: "Dr. Kiki",
      tindakan: "Angioplasty",
      ruangan: "Endoscopy I",
    },
    {
      jamMulai: "10:00",
      jamSelesai: "11:00",
      estimasi: 60,
      dokterOperator: "Dr. Lina",
      tindakan: "Adenoidectomy",
      ruangan: "Endoscopy II",
    },
    {
      jamMulai: "11:15",
      jamSelesai: "12:15",
      estimasi: 60,
      dokterOperator: "Dr. Maman",
      tindakan: "Spinal Fusion",
      ruangan: "Endoscopy III",
    },
    {
      jamMulai: "13:00",
      jamSelesai: "14:30",
      estimasi: 90,
      dokterOperator: "Dr. Nana",
      tindakan: "Breast Biopsy",
      ruangan: "Endoscopy IV",
    },
    {
      jamMulai: "14:45",
      jamSelesai: "15:45",
      estimasi: 60,
      dokterOperator: "Dr. Oka",
      tindakan: "Prostatectomy",
      ruangan: "Endoscopy V",
    },
  ],
};
