export const pemeriksaRadiologi = [
  {
    id: "tdk_1",
    pemeriksaanRadiologi: "X-Ray Thorax",
    dokterPemeriksa: "Dr. John Doe",
    harga: 150000,
  },
  {
    id: "tdk_2",
    pemeriksaanRadiologi: "MRI Abdomen",
    dokterPemeriksa: "Dr. Jane Smith",
    harga: 750000,
  },
  {
    id: "tdk_3",
    pemeriksaanRadiologi: "CT Scan Kepala",
    dokterPemeriksa: "Dr. Emily Brown",
    harga: 500000,
  },
  {
    id: "tdk_4",
    pemeriksaanRadiologi: "Ultrasound Abdomen",
    dokterPemeriksa: "Dr. Michael Johnson",
    harga: 250000,
  },
  {
    id: "tdk_5",
    pemeriksaanRadiologi: "X-Ray Tangan",
    dokterPemeriksa: "Dr. Sarah Lee",
    harga: 120000,
  },
  {
    id: "tdk_6",
    pemeriksaanRadiologi: "MRI Kepala",
    dokterPemeriksa: "Dr. Andrew Wilson",
    harga: 800000,
  },
  {
    id: "tdk_7",
    pemeriksaanRadiologi: "CT Scan Abdomen",
    dokterPemeriksa: "Dr. Jessica Davis",
    harga: 600000,
  },
  {
    id: "tdk_8",
    pemeriksaanRadiologi: "Ultrasound Jantung",
    dokterPemeriksa: "Dr. William Brown",
    harga: 300000,
  },
  {
    id: "tdk_9",
    pemeriksaanRadiologi: "X-Ray Lutut",
    dokterPemeriksa: "Dr. Olivia Harris",
    harga: 130000,
  },
  {
    id: "tdk_10",
    pemeriksaanRadiologi: "MRI Tulang Belakang",
    dokterPemeriksa: "Dr. Ethan Clark",
    harga: 900000,
  },
  {
    id: "tdk_11",
    pemeriksaanRadiologi: "CT Scan Paru-Paru",
    dokterPemeriksa: "Dr. Sophia Lewis",
    harga: 550000,
  },
  {
    id: "tdk_12",
    pemeriksaanRadiologi: "Ultrasound Ginjal",
    dokterPemeriksa: "Dr. Benjamin Scott",
    harga: 280000,
  },
  {
    id: "tdk_13",
    pemeriksaanRadiologi: "X-Ray Pinggul",
    dokterPemeriksa: "Dr. Emma Hall",
    harga: 140000,
  },
  {
    id: "tdk_14",
    pemeriksaanRadiologi: "MRI Jantung",
    dokterPemeriksa: "Dr. Liam King",
    harga: 850000,
  },
  {
    id: "tdk_15",
    pemeriksaanRadiologi: "CT Scan Otak",
    dokterPemeriksa: "Dr. Ava Wright",
    harga: 700000,
  },
];
