export const tindakanDataConfig = [
  { id: "tdk_1", name: "Analisa DNA Thalassemia" },
  { id: "tdk_2", name: "Heat Instability Test" },
  { id: "tdk_3", name: "Inklusi HB H" },
  { id: "tdk_4", name: "Isopropanol" },
  { id: "tdk_5", name: "Skrining Thalassemia (Paket)" },
  { id: "tdk_6", name: "Thal Alfa MLPA" },
  { id: "tdk_7", name: "Thal Alfa Sequencing" },
  { id: "tdk_8", name: "Test HB A2" },
  { id: "tdk_9", name: "Test HB F" },
  { id: "tdk_10", name: "Test Elektroforesis HB" },
  { id: "tdk_11", name: "Analisa Cairan Otak" },
  { id: "tdk_12", name: "Analisa Cairan Sendi" },
  { id: "tdk_13", name: "Analisa Cairan Perut" },
  { id: "tdk_14", name: "Anti MOG" },
  { id: "tdk_15", name: "G Oligoclonal Band" },
  { id: "tdk_16", name: "Parasitologi Lain-Lain" },
  { id: "tdk_17", name: "Sitologi Cairan Tubuh (MGG)" },
  { id: "tdk_18", name: "Transudat Eksudat" },
  { id: "tdk_19", name: "Cairan Tubuh Profile" },
  { id: "tdk_20", name: "Analisa Biokimia Cairan" },
  { id: "tdk_21", name: "Osteocalcin" },
  { id: "tdk_22", name: "Paket Sitokin" },
  { id: "tdk_23", name: "D GFG II" },
  { id: "tdk_24", name: "D GFG Placenta Growth Factor" },
  { id: "tdk_25", name: "Profil ANA" },
  { id: "tdk_26", name: "Rasio SFLT1 / PIGF" },
  { id: "tdk_27", name: "D G Ratio PIGF" },
  { id: "tdk_28", name: "SEL T Sub Total" },
  { id: "tdk_29", name: "SEL T8" },
  { id: "tdk_30", name: "SEL T4" },
  { id: "tdk_31", name: "Paket MCU PetroGas Annual" },
  { id: "tdk_32", name: "Paket MCU PetroGas Executive" },
  { id: "tdk_33", name: "Paket MCU Pemeriksaan Dasar" },
  { id: "tdk_34", name: "Paket MCU Perempuan" },
  { id: "tdk_35", name: "Paket MCU Karyawan Tambang" },
  { id: "tdk_36", name: "Paket MCU Tahunan" },
  { id: "tdk_37", name: "Paket MCU Pemeriksaan Lanjutan" },
  { id: "tdk_38", name: "Paket MCU Hemat" },
  { id: "tdk_39", name: "Paket MCU Dasar" },
  { id: "tdk_40", name: "Paket MCU Anak" },
  { id: "tdk_41", name: "D1 Chikungunya Antibody IgM" },
  { id: "tdk_42", name: "D1 CRP Kuantitatif" },
  { id: "tdk_43", name: "D1 Dengue NS1 Antigen" },
  { id: "tdk_44", name: "D1 IgG Dengue" },
  { id: "tdk_45", name: "D1 IgM Dengue" },
  { id: "tdk_46", name: "D1 Typhi Antibody IgM" },
  { id: "tdk_47", name: "D1 Typhi Antibody IgG" },
  { id: "tdk_48", name: "D1 Widal" },
  { id: "tdk_49", name: "D1 Widal (All Variants)" },
  { id: "tdk_50", name: "D1 Toxoplasma IgM" },
];
