name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - Production  # Workflow ini akan berjalan setiap ada perubahan di branch 'QuilvianDev'

jobs:
  build:
    runs-on: ubuntu-latest  # Workflow ini akan dijalankan di Ubuntu terbaru

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "ikbalyuliyanto7"  # Gunakan Docker Hub username dari GitHub Secrets
          password: "dckr_pat_lXH2eBGsna_Q5z3SDXGN6Vix6Cc"  # Gunakan Docker Hub password/token dari GitHub Secrets

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ikbalyuliyanto7/quilvian-frontend-api:latest .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ikbalyuliyanto7/quilvian-frontend-api:latest
