# name: Deploy Next.js to Docker Hub

# on:
#   push:
#     branches:
#       - Production  # Sesuaikan dengan branch yang ingin di-deploy

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#           cache: 'yarn'

#       - name: Install dependencies
#         run: yarn install --frozen-lockfile

#       - name: Build Next.js
#         run: yarn build

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: "ikbalyuliyanto7"  # Gunakan Docker Hub username dari GitHub Secrets
#           password: "dckr_pat_lXH2eBGsna_Q5z3SDXGN6Vix6Cc"

#       - name: Build and push Docker image
#         run: |
#           docker build -t ikbalyuliyanto7/quilvian-frontend-api .
#           docker tag ikbalyuliyanto7/quilvian-frontend-api ikbalyuliyanto7/quilvian-frontend-api:latest
#           docker push ikbalyuliyanto7/quilvian-frontend-api

name: Deploy Next.js to Docker Hub

on:
  push:
    branches:
      - Production # Sesuaikan dengan branch yang ingin di-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ikbalyuliyanto7 # Gunakan Docker Hub username dari GitHub Secrets
          password: dckr_pat_lXH2eBGsna_Q5z3SDXGN6Vix6Cc

      - name: Build and push NextJS image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.nextjs
          push: true
          tags: ikbalyuliyanto7/quilvian-frontend-api:next

      - name: Build and push Nginx image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.nginx
          push: true
          tags: ikbalyuliyanto7/quilvian-frontend-api:nginx

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/project
            echo "Pulling latest images..."
            docker pull ikbalyuliyanto7/quilvian-frontend-api:next
            docker pull ikbalyuliyanto7/quilvian-frontend-api:nginx
            echo "Stopping and removing containers..."
            docker-compose -f docker-compose.prod.yml down
            echo "Starting updated containers..."
            docker-compose -f docker-compose.prod.yml up -d
            echo "Deployment completed successfully!"
